/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.com.elarian.hera.proto.IndexMapping');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest.displayName = 'proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    appId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    tag: (f = msg.getTag()) && proto.com.elarian.hera.proto.IndexMapping.toObject(includeInstance, f),
    productId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    key: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest}
 */
proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest;
  return proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest}
 */
proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAppId(value);
      break;
    case 2:
      var value = new proto.com.elarian.hera.proto.IndexMapping;
      reader.readMessage(value,proto.com.elarian.hera.proto.IndexMapping.deserializeBinaryFromReader);
      msg.setTag(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setProductId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAppId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTag();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.com.elarian.hera.proto.IndexMapping.serializeBinaryToWriter
    );
  }
  f = message.getProductId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string app_id = 1;
 * @return {string}
 */
proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest.prototype.getAppId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest.prototype.setAppId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional IndexMapping tag = 2;
 * @return {?proto.com.elarian.hera.proto.IndexMapping}
 */
proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest.prototype.getTag = function() {
  return /** @type{?proto.com.elarian.hera.proto.IndexMapping} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.IndexMapping, 2));
};


/** @param {?proto.com.elarian.hera.proto.IndexMapping|undefined} value */
proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest.prototype.setTag = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest.prototype.clearTag = function() {
  this.setTag(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest.prototype.hasTag = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string product_id = 3;
 * @return {string}
 */
proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest.prototype.getProductId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest.prototype.setProductId = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string key = 4;
 * @return {string}
 */
proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.com.elarian.hera.proto.CancelCustomerReminderTagRequest.prototype.setKey = function(value) {
  jspb.Message.setField(this, 4, value);
};


