/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.com.elarian.hera.proto.CheckoutPaymentRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.com.elarian.hera.proto.Cash');
goog.require('proto.com.elarian.hera.proto.CustomerNumber');
goog.require('proto.com.elarian.hera.proto.PaymentChannelNumber');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.CheckoutPaymentRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.com.elarian.hera.proto.CheckoutPaymentRequest.oneofGroups_);
};
goog.inherits(proto.com.elarian.hera.proto.CheckoutPaymentRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.elarian.hera.proto.CheckoutPaymentRequest.displayName = 'proto.com.elarian.hera.proto.CheckoutPaymentRequest';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.com.elarian.hera.proto.CheckoutPaymentRequest.oneofGroups_ = [[3,4]];

/**
 * @enum {number}
 */
proto.com.elarian.hera.proto.CheckoutPaymentRequest.CustomerCase = {
  CUSTOMER_NOT_SET: 0,
  CUSTOMER_ID: 3,
  CUSTOMER_NUMBER: 4
};

/**
 * @return {proto.com.elarian.hera.proto.CheckoutPaymentRequest.CustomerCase}
 */
proto.com.elarian.hera.proto.CheckoutPaymentRequest.prototype.getCustomerCase = function() {
  return /** @type {proto.com.elarian.hera.proto.CheckoutPaymentRequest.CustomerCase} */(jspb.Message.computeOneofCase(this, proto.com.elarian.hera.proto.CheckoutPaymentRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.CheckoutPaymentRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.CheckoutPaymentRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.CheckoutPaymentRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.CheckoutPaymentRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    appId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    productId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    customerId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    customerNumber: (f = msg.getCustomerNumber()) && proto.com.elarian.hera.proto.CustomerNumber.toObject(includeInstance, f),
    channelNumber: (f = msg.getChannelNumber()) && proto.com.elarian.hera.proto.PaymentChannelNumber.toObject(includeInstance, f),
    value: (f = msg.getValue()) && proto.com.elarian.hera.proto.Cash.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.CheckoutPaymentRequest}
 */
proto.com.elarian.hera.proto.CheckoutPaymentRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.CheckoutPaymentRequest;
  return proto.com.elarian.hera.proto.CheckoutPaymentRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.CheckoutPaymentRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.CheckoutPaymentRequest}
 */
proto.com.elarian.hera.proto.CheckoutPaymentRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAppId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setProductId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCustomerId(value);
      break;
    case 4:
      var value = new proto.com.elarian.hera.proto.CustomerNumber;
      reader.readMessage(value,proto.com.elarian.hera.proto.CustomerNumber.deserializeBinaryFromReader);
      msg.setCustomerNumber(value);
      break;
    case 5:
      var value = new proto.com.elarian.hera.proto.PaymentChannelNumber;
      reader.readMessage(value,proto.com.elarian.hera.proto.PaymentChannelNumber.deserializeBinaryFromReader);
      msg.setChannelNumber(value);
      break;
    case 6:
      var value = new proto.com.elarian.hera.proto.Cash;
      reader.readMessage(value,proto.com.elarian.hera.proto.Cash.deserializeBinaryFromReader);
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.CheckoutPaymentRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.CheckoutPaymentRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.CheckoutPaymentRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.CheckoutPaymentRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAppId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getProductId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCustomerNumber();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.com.elarian.hera.proto.CustomerNumber.serializeBinaryToWriter
    );
  }
  f = message.getChannelNumber();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.com.elarian.hera.proto.PaymentChannelNumber.serializeBinaryToWriter
    );
  }
  f = message.getValue();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.com.elarian.hera.proto.Cash.serializeBinaryToWriter
    );
  }
};


/**
 * optional string app_id = 1;
 * @return {string}
 */
proto.com.elarian.hera.proto.CheckoutPaymentRequest.prototype.getAppId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.elarian.hera.proto.CheckoutPaymentRequest.prototype.setAppId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string product_id = 2;
 * @return {string}
 */
proto.com.elarian.hera.proto.CheckoutPaymentRequest.prototype.getProductId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.com.elarian.hera.proto.CheckoutPaymentRequest.prototype.setProductId = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string customer_id = 3;
 * @return {string}
 */
proto.com.elarian.hera.proto.CheckoutPaymentRequest.prototype.getCustomerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.com.elarian.hera.proto.CheckoutPaymentRequest.prototype.setCustomerId = function(value) {
  jspb.Message.setOneofField(this, 3, proto.com.elarian.hera.proto.CheckoutPaymentRequest.oneofGroups_[0], value);
};


proto.com.elarian.hera.proto.CheckoutPaymentRequest.prototype.clearCustomerId = function() {
  jspb.Message.setOneofField(this, 3, proto.com.elarian.hera.proto.CheckoutPaymentRequest.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.CheckoutPaymentRequest.prototype.hasCustomerId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional CustomerNumber customer_number = 4;
 * @return {?proto.com.elarian.hera.proto.CustomerNumber}
 */
proto.com.elarian.hera.proto.CheckoutPaymentRequest.prototype.getCustomerNumber = function() {
  return /** @type{?proto.com.elarian.hera.proto.CustomerNumber} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.CustomerNumber, 4));
};


/** @param {?proto.com.elarian.hera.proto.CustomerNumber|undefined} value */
proto.com.elarian.hera.proto.CheckoutPaymentRequest.prototype.setCustomerNumber = function(value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.com.elarian.hera.proto.CheckoutPaymentRequest.oneofGroups_[0], value);
};


proto.com.elarian.hera.proto.CheckoutPaymentRequest.prototype.clearCustomerNumber = function() {
  this.setCustomerNumber(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.CheckoutPaymentRequest.prototype.hasCustomerNumber = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional PaymentChannelNumber channel_number = 5;
 * @return {?proto.com.elarian.hera.proto.PaymentChannelNumber}
 */
proto.com.elarian.hera.proto.CheckoutPaymentRequest.prototype.getChannelNumber = function() {
  return /** @type{?proto.com.elarian.hera.proto.PaymentChannelNumber} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.PaymentChannelNumber, 5));
};


/** @param {?proto.com.elarian.hera.proto.PaymentChannelNumber|undefined} value */
proto.com.elarian.hera.proto.CheckoutPaymentRequest.prototype.setChannelNumber = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.com.elarian.hera.proto.CheckoutPaymentRequest.prototype.clearChannelNumber = function() {
  this.setChannelNumber(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.CheckoutPaymentRequest.prototype.hasChannelNumber = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional Cash value = 6;
 * @return {?proto.com.elarian.hera.proto.Cash}
 */
proto.com.elarian.hera.proto.CheckoutPaymentRequest.prototype.getValue = function() {
  return /** @type{?proto.com.elarian.hera.proto.Cash} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.Cash, 6));
};


/** @param {?proto.com.elarian.hera.proto.Cash|undefined} value */
proto.com.elarian.hera.proto.CheckoutPaymentRequest.prototype.setValue = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.com.elarian.hera.proto.CheckoutPaymentRequest.prototype.clearValue = function() {
  this.setValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.CheckoutPaymentRequest.prototype.hasValue = function() {
  return jspb.Message.getField(this, 6) != null;
};


