/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.com.elarian.hera.proto.DequeueCallAction');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.com.elarian.hera.proto.VoiceChannelNumber');
goog.require('proto.google.protobuf.StringValue');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.DequeueCallAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.elarian.hera.proto.DequeueCallAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.elarian.hera.proto.DequeueCallAction.displayName = 'proto.com.elarian.hera.proto.DequeueCallAction';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.DequeueCallAction.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.DequeueCallAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.DequeueCallAction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.DequeueCallAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    channelNumber: (f = msg.getChannelNumber()) && proto.com.elarian.hera.proto.VoiceChannelNumber.toObject(includeInstance, f),
    record: jspb.Message.getFieldWithDefault(msg, 2, false),
    queueName: (f = msg.getQueueName()) && proto.google.protobuf.StringValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.DequeueCallAction}
 */
proto.com.elarian.hera.proto.DequeueCallAction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.DequeueCallAction;
  return proto.com.elarian.hera.proto.DequeueCallAction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.DequeueCallAction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.DequeueCallAction}
 */
proto.com.elarian.hera.proto.DequeueCallAction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.elarian.hera.proto.VoiceChannelNumber;
      reader.readMessage(value,proto.com.elarian.hera.proto.VoiceChannelNumber.deserializeBinaryFromReader);
      msg.setChannelNumber(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRecord(value);
      break;
    case 3:
      var value = new proto.google.protobuf.StringValue;
      reader.readMessage(value,proto.google.protobuf.StringValue.deserializeBinaryFromReader);
      msg.setQueueName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.DequeueCallAction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.DequeueCallAction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.DequeueCallAction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.DequeueCallAction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getChannelNumber();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.com.elarian.hera.proto.VoiceChannelNumber.serializeBinaryToWriter
    );
  }
  f = message.getRecord();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getQueueName();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.google.protobuf.StringValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional VoiceChannelNumber channel_number = 1;
 * @return {?proto.com.elarian.hera.proto.VoiceChannelNumber}
 */
proto.com.elarian.hera.proto.DequeueCallAction.prototype.getChannelNumber = function() {
  return /** @type{?proto.com.elarian.hera.proto.VoiceChannelNumber} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.VoiceChannelNumber, 1));
};


/** @param {?proto.com.elarian.hera.proto.VoiceChannelNumber|undefined} value */
proto.com.elarian.hera.proto.DequeueCallAction.prototype.setChannelNumber = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.com.elarian.hera.proto.DequeueCallAction.prototype.clearChannelNumber = function() {
  this.setChannelNumber(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.DequeueCallAction.prototype.hasChannelNumber = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool record = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.DequeueCallAction.prototype.getRecord = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.com.elarian.hera.proto.DequeueCallAction.prototype.setRecord = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional google.protobuf.StringValue queue_name = 3;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.com.elarian.hera.proto.DequeueCallAction.prototype.getQueueName = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.StringValue, 3));
};


/** @param {?proto.google.protobuf.StringValue|undefined} value */
proto.com.elarian.hera.proto.DequeueCallAction.prototype.setQueueName = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.com.elarian.hera.proto.DequeueCallAction.prototype.clearQueueName = function() {
  this.setQueueName(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.DequeueCallAction.prototype.hasQueueName = function() {
  return jspb.Message.getField(this, 3) != null;
};


