/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.com.elarian.hera.proto.DialCallAction');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.com.elarian.hera.proto.CustomerNumber');
goog.require('proto.google.protobuf.Int32Value');
goog.require('proto.google.protobuf.StringValue');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.DialCallAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.elarian.hera.proto.DialCallAction.repeatedFields_, null);
};
goog.inherits(proto.com.elarian.hera.proto.DialCallAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.elarian.hera.proto.DialCallAction.displayName = 'proto.com.elarian.hera.proto.DialCallAction';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.elarian.hera.proto.DialCallAction.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.DialCallAction.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.DialCallAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.DialCallAction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.DialCallAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    customerNumbersList: jspb.Message.toObjectList(msg.getCustomerNumbersList(),
    proto.com.elarian.hera.proto.CustomerNumber.toObject, includeInstance),
    record: jspb.Message.getFieldWithDefault(msg, 2, false),
    sequential: jspb.Message.getFieldWithDefault(msg, 3, false),
    ringbackTone: (f = msg.getRingbackTone()) && proto.google.protobuf.StringValue.toObject(includeInstance, f),
    callerId: (f = msg.getCallerId()) && proto.google.protobuf.StringValue.toObject(includeInstance, f),
    maxDuration: (f = msg.getMaxDuration()) && proto.google.protobuf.Int32Value.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.DialCallAction}
 */
proto.com.elarian.hera.proto.DialCallAction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.DialCallAction;
  return proto.com.elarian.hera.proto.DialCallAction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.DialCallAction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.DialCallAction}
 */
proto.com.elarian.hera.proto.DialCallAction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.elarian.hera.proto.CustomerNumber;
      reader.readMessage(value,proto.com.elarian.hera.proto.CustomerNumber.deserializeBinaryFromReader);
      msg.addCustomerNumbers(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRecord(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSequential(value);
      break;
    case 4:
      var value = new proto.google.protobuf.StringValue;
      reader.readMessage(value,proto.google.protobuf.StringValue.deserializeBinaryFromReader);
      msg.setRingbackTone(value);
      break;
    case 5:
      var value = new proto.google.protobuf.StringValue;
      reader.readMessage(value,proto.google.protobuf.StringValue.deserializeBinaryFromReader);
      msg.setCallerId(value);
      break;
    case 6:
      var value = new proto.google.protobuf.Int32Value;
      reader.readMessage(value,proto.google.protobuf.Int32Value.deserializeBinaryFromReader);
      msg.setMaxDuration(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.DialCallAction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.DialCallAction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.DialCallAction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.DialCallAction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCustomerNumbersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.com.elarian.hera.proto.CustomerNumber.serializeBinaryToWriter
    );
  }
  f = message.getRecord();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getSequential();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getRingbackTone();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.google.protobuf.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getCallerId();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.google.protobuf.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getMaxDuration();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.google.protobuf.Int32Value.serializeBinaryToWriter
    );
  }
};


/**
 * repeated CustomerNumber customer_numbers = 1;
 * @return {!Array.<!proto.com.elarian.hera.proto.CustomerNumber>}
 */
proto.com.elarian.hera.proto.DialCallAction.prototype.getCustomerNumbersList = function() {
  return /** @type{!Array.<!proto.com.elarian.hera.proto.CustomerNumber>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.elarian.hera.proto.CustomerNumber, 1));
};


/** @param {!Array.<!proto.com.elarian.hera.proto.CustomerNumber>} value */
proto.com.elarian.hera.proto.DialCallAction.prototype.setCustomerNumbersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.com.elarian.hera.proto.CustomerNumber=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.elarian.hera.proto.CustomerNumber}
 */
proto.com.elarian.hera.proto.DialCallAction.prototype.addCustomerNumbers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.com.elarian.hera.proto.CustomerNumber, opt_index);
};


proto.com.elarian.hera.proto.DialCallAction.prototype.clearCustomerNumbersList = function() {
  this.setCustomerNumbersList([]);
};


/**
 * optional bool record = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.DialCallAction.prototype.getRecord = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.com.elarian.hera.proto.DialCallAction.prototype.setRecord = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional bool sequential = 3;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.DialCallAction.prototype.getSequential = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 3, false));
};


/** @param {boolean} value */
proto.com.elarian.hera.proto.DialCallAction.prototype.setSequential = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional google.protobuf.StringValue ringback_tone = 4;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.com.elarian.hera.proto.DialCallAction.prototype.getRingbackTone = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.StringValue, 4));
};


/** @param {?proto.google.protobuf.StringValue|undefined} value */
proto.com.elarian.hera.proto.DialCallAction.prototype.setRingbackTone = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.com.elarian.hera.proto.DialCallAction.prototype.clearRingbackTone = function() {
  this.setRingbackTone(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.DialCallAction.prototype.hasRingbackTone = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.StringValue caller_id = 5;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.com.elarian.hera.proto.DialCallAction.prototype.getCallerId = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.StringValue, 5));
};


/** @param {?proto.google.protobuf.StringValue|undefined} value */
proto.com.elarian.hera.proto.DialCallAction.prototype.setCallerId = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.com.elarian.hera.proto.DialCallAction.prototype.clearCallerId = function() {
  this.setCallerId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.DialCallAction.prototype.hasCallerId = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.Int32Value max_duration = 6;
 * @return {?proto.google.protobuf.Int32Value}
 */
proto.com.elarian.hera.proto.DialCallAction.prototype.getMaxDuration = function() {
  return /** @type{?proto.google.protobuf.Int32Value} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Int32Value, 6));
};


/** @param {?proto.google.protobuf.Int32Value|undefined} value */
proto.com.elarian.hera.proto.DialCallAction.prototype.setMaxDuration = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.com.elarian.hera.proto.DialCallAction.prototype.clearMaxDuration = function() {
  this.setMaxDuration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.DialCallAction.prototype.hasMaxDuration = function() {
  return jspb.Message.getField(this, 6) != null;
};


