// source: identity_event.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var common_model_pb = require('./common_model_pb.js');
goog.object.extend(proto, common_model_pb);
goog.exportSymbol('proto.com.elarian.hera.proto.GroupDeletedEvent', null, global);
goog.exportSymbol('proto.com.elarian.hera.proto.GroupUpdatedEvent', null, global);
goog.exportSymbol('proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent', null, global);
goog.exportSymbol('proto.com.elarian.hera.proto.IdentityEvent', null, global);
goog.exportSymbol('proto.com.elarian.hera.proto.IdentityEvent.EventCase', null, global);
goog.exportSymbol('proto.com.elarian.hera.proto.MetadataDeletedEvent', null, global);
goog.exportSymbol('proto.com.elarian.hera.proto.MetadataUpdatedEvent', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.IdentityEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.com.elarian.hera.proto.IdentityEvent.oneofGroups_);
};
goog.inherits(proto.com.elarian.hera.proto.IdentityEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.elarian.hera.proto.IdentityEvent.displayName = 'proto.com.elarian.hera.proto.IdentityEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent.displayName = 'proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.GroupUpdatedEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.elarian.hera.proto.GroupUpdatedEvent.repeatedFields_, null);
};
goog.inherits(proto.com.elarian.hera.proto.GroupUpdatedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.elarian.hera.proto.GroupUpdatedEvent.displayName = 'proto.com.elarian.hera.proto.GroupUpdatedEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.GroupDeletedEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.elarian.hera.proto.GroupDeletedEvent.repeatedFields_, null);
};
goog.inherits(proto.com.elarian.hera.proto.GroupDeletedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.elarian.hera.proto.GroupDeletedEvent.displayName = 'proto.com.elarian.hera.proto.GroupDeletedEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.MetadataUpdatedEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.elarian.hera.proto.MetadataUpdatedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.elarian.hera.proto.MetadataUpdatedEvent.displayName = 'proto.com.elarian.hera.proto.MetadataUpdatedEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.MetadataDeletedEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.elarian.hera.proto.MetadataDeletedEvent.repeatedFields_, null);
};
goog.inherits(proto.com.elarian.hera.proto.MetadataDeletedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.elarian.hera.proto.MetadataDeletedEvent.displayName = 'proto.com.elarian.hera.proto.MetadataDeletedEvent';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.com.elarian.hera.proto.IdentityEvent.oneofGroups_ = [[1,2,3,4,5]];

/**
 * @enum {number}
 */
proto.com.elarian.hera.proto.IdentityEvent.EventCase = {
  EVENT_NOT_SET: 0,
  ENTITY_DECOMMISSIONED: 1,
  GROUP_UPDATED: 2,
  GROUP_DELETED: 3,
  METADATA_UPDATED: 4,
  METADATA_DELETED: 5
};

/**
 * @return {proto.com.elarian.hera.proto.IdentityEvent.EventCase}
 */
proto.com.elarian.hera.proto.IdentityEvent.prototype.getEventCase = function() {
  return /** @type {proto.com.elarian.hera.proto.IdentityEvent.EventCase} */(jspb.Message.computeOneofCase(this, proto.com.elarian.hera.proto.IdentityEvent.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.IdentityEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.IdentityEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.IdentityEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.IdentityEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    entityDecommissioned: (f = msg.getEntityDecommissioned()) && proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent.toObject(includeInstance, f),
    groupUpdated: (f = msg.getGroupUpdated()) && proto.com.elarian.hera.proto.GroupUpdatedEvent.toObject(includeInstance, f),
    groupDeleted: (f = msg.getGroupDeleted()) && proto.com.elarian.hera.proto.GroupDeletedEvent.toObject(includeInstance, f),
    metadataUpdated: (f = msg.getMetadataUpdated()) && proto.com.elarian.hera.proto.MetadataUpdatedEvent.toObject(includeInstance, f),
    metadataDeleted: (f = msg.getMetadataDeleted()) && proto.com.elarian.hera.proto.MetadataDeletedEvent.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.IdentityEvent}
 */
proto.com.elarian.hera.proto.IdentityEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.IdentityEvent;
  return proto.com.elarian.hera.proto.IdentityEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.IdentityEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.IdentityEvent}
 */
proto.com.elarian.hera.proto.IdentityEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent;
      reader.readMessage(value,proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent.deserializeBinaryFromReader);
      msg.setEntityDecommissioned(value);
      break;
    case 2:
      var value = new proto.com.elarian.hera.proto.GroupUpdatedEvent;
      reader.readMessage(value,proto.com.elarian.hera.proto.GroupUpdatedEvent.deserializeBinaryFromReader);
      msg.setGroupUpdated(value);
      break;
    case 3:
      var value = new proto.com.elarian.hera.proto.GroupDeletedEvent;
      reader.readMessage(value,proto.com.elarian.hera.proto.GroupDeletedEvent.deserializeBinaryFromReader);
      msg.setGroupDeleted(value);
      break;
    case 4:
      var value = new proto.com.elarian.hera.proto.MetadataUpdatedEvent;
      reader.readMessage(value,proto.com.elarian.hera.proto.MetadataUpdatedEvent.deserializeBinaryFromReader);
      msg.setMetadataUpdated(value);
      break;
    case 5:
      var value = new proto.com.elarian.hera.proto.MetadataDeletedEvent;
      reader.readMessage(value,proto.com.elarian.hera.proto.MetadataDeletedEvent.deserializeBinaryFromReader);
      msg.setMetadataDeleted(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.IdentityEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.IdentityEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.IdentityEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.IdentityEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEntityDecommissioned();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent.serializeBinaryToWriter
    );
  }
  f = message.getGroupUpdated();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.com.elarian.hera.proto.GroupUpdatedEvent.serializeBinaryToWriter
    );
  }
  f = message.getGroupDeleted();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.com.elarian.hera.proto.GroupDeletedEvent.serializeBinaryToWriter
    );
  }
  f = message.getMetadataUpdated();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.com.elarian.hera.proto.MetadataUpdatedEvent.serializeBinaryToWriter
    );
  }
  f = message.getMetadataDeleted();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.com.elarian.hera.proto.MetadataDeletedEvent.serializeBinaryToWriter
    );
  }
};


/**
 * optional IdentityEntityDecommissionedEvent entity_decommissioned = 1;
 * @return {?proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent}
 */
proto.com.elarian.hera.proto.IdentityEvent.prototype.getEntityDecommissioned = function() {
  return /** @type{?proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent, 1));
};


/**
 * @param {?proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent|undefined} value
 * @return {!proto.com.elarian.hera.proto.IdentityEvent} returns this
*/
proto.com.elarian.hera.proto.IdentityEvent.prototype.setEntityDecommissioned = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.com.elarian.hera.proto.IdentityEvent.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.IdentityEvent} returns this
 */
proto.com.elarian.hera.proto.IdentityEvent.prototype.clearEntityDecommissioned = function() {
  return this.setEntityDecommissioned(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.IdentityEvent.prototype.hasEntityDecommissioned = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional GroupUpdatedEvent group_updated = 2;
 * @return {?proto.com.elarian.hera.proto.GroupUpdatedEvent}
 */
proto.com.elarian.hera.proto.IdentityEvent.prototype.getGroupUpdated = function() {
  return /** @type{?proto.com.elarian.hera.proto.GroupUpdatedEvent} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.GroupUpdatedEvent, 2));
};


/**
 * @param {?proto.com.elarian.hera.proto.GroupUpdatedEvent|undefined} value
 * @return {!proto.com.elarian.hera.proto.IdentityEvent} returns this
*/
proto.com.elarian.hera.proto.IdentityEvent.prototype.setGroupUpdated = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.com.elarian.hera.proto.IdentityEvent.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.IdentityEvent} returns this
 */
proto.com.elarian.hera.proto.IdentityEvent.prototype.clearGroupUpdated = function() {
  return this.setGroupUpdated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.IdentityEvent.prototype.hasGroupUpdated = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional GroupDeletedEvent group_deleted = 3;
 * @return {?proto.com.elarian.hera.proto.GroupDeletedEvent}
 */
proto.com.elarian.hera.proto.IdentityEvent.prototype.getGroupDeleted = function() {
  return /** @type{?proto.com.elarian.hera.proto.GroupDeletedEvent} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.GroupDeletedEvent, 3));
};


/**
 * @param {?proto.com.elarian.hera.proto.GroupDeletedEvent|undefined} value
 * @return {!proto.com.elarian.hera.proto.IdentityEvent} returns this
*/
proto.com.elarian.hera.proto.IdentityEvent.prototype.setGroupDeleted = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.com.elarian.hera.proto.IdentityEvent.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.IdentityEvent} returns this
 */
proto.com.elarian.hera.proto.IdentityEvent.prototype.clearGroupDeleted = function() {
  return this.setGroupDeleted(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.IdentityEvent.prototype.hasGroupDeleted = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional MetadataUpdatedEvent metadata_updated = 4;
 * @return {?proto.com.elarian.hera.proto.MetadataUpdatedEvent}
 */
proto.com.elarian.hera.proto.IdentityEvent.prototype.getMetadataUpdated = function() {
  return /** @type{?proto.com.elarian.hera.proto.MetadataUpdatedEvent} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.MetadataUpdatedEvent, 4));
};


/**
 * @param {?proto.com.elarian.hera.proto.MetadataUpdatedEvent|undefined} value
 * @return {!proto.com.elarian.hera.proto.IdentityEvent} returns this
*/
proto.com.elarian.hera.proto.IdentityEvent.prototype.setMetadataUpdated = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.com.elarian.hera.proto.IdentityEvent.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.IdentityEvent} returns this
 */
proto.com.elarian.hera.proto.IdentityEvent.prototype.clearMetadataUpdated = function() {
  return this.setMetadataUpdated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.IdentityEvent.prototype.hasMetadataUpdated = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional MetadataDeletedEvent metadata_deleted = 5;
 * @return {?proto.com.elarian.hera.proto.MetadataDeletedEvent}
 */
proto.com.elarian.hera.proto.IdentityEvent.prototype.getMetadataDeleted = function() {
  return /** @type{?proto.com.elarian.hera.proto.MetadataDeletedEvent} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.MetadataDeletedEvent, 5));
};


/**
 * @param {?proto.com.elarian.hera.proto.MetadataDeletedEvent|undefined} value
 * @return {!proto.com.elarian.hera.proto.IdentityEvent} returns this
*/
proto.com.elarian.hera.proto.IdentityEvent.prototype.setMetadataDeleted = function(value) {
  return jspb.Message.setOneofWrapperField(this, 5, proto.com.elarian.hera.proto.IdentityEvent.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.IdentityEvent} returns this
 */
proto.com.elarian.hera.proto.IdentityEvent.prototype.clearMetadataDeleted = function() {
  return this.setMetadataDeleted(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.IdentityEvent.prototype.hasMetadataDeleted = function() {
  return jspb.Message.getField(this, 5) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    humanId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    orgId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    cxnProps: (f = msg.getCxnProps()) && common_model_pb.AppConnectionProps.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent}
 */
proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent;
  return proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent}
 */
proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setHumanId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrgId(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 4:
      var value = new common_model_pb.AppConnectionProps;
      reader.readMessage(value,common_model_pb.AppConnectionProps.deserializeBinaryFromReader);
      msg.setCxnProps(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHumanId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOrgId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCxnProps();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      common_model_pb.AppConnectionProps.serializeBinaryToWriter
    );
  }
};


/**
 * optional string human_id = 1;
 * @return {string}
 */
proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent.prototype.getHumanId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent} returns this
 */
proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent.prototype.setHumanId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string org_id = 2;
 * @return {string}
 */
proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent.prototype.getOrgId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent} returns this
 */
proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent.prototype.setOrgId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.Timestamp timestamp = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent} returns this
*/
proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent} returns this
 */
proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional AppConnectionProps cxn_props = 4;
 * @return {?proto.com.elarian.hera.proto.AppConnectionProps}
 */
proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent.prototype.getCxnProps = function() {
  return /** @type{?proto.com.elarian.hera.proto.AppConnectionProps} */ (
    jspb.Message.getWrapperField(this, common_model_pb.AppConnectionProps, 4));
};


/**
 * @param {?proto.com.elarian.hera.proto.AppConnectionProps|undefined} value
 * @return {!proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent} returns this
*/
proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent.prototype.setCxnProps = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent} returns this
 */
proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent.prototype.clearCxnProps = function() {
  return this.setCxnProps(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.IdentityEntityDecommissionedEvent.prototype.hasCxnProps = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.elarian.hera.proto.GroupUpdatedEvent.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.GroupUpdatedEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.GroupUpdatedEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.GroupUpdatedEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.GroupUpdatedEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    humanId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    orgId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    cxnProps: (f = msg.getCxnProps()) && common_model_pb.AppConnectionProps.toObject(includeInstance, f),
    updatesList: jspb.Message.toObjectList(msg.getUpdatesList(),
    common_model_pb.GroupIndex.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.GroupUpdatedEvent}
 */
proto.com.elarian.hera.proto.GroupUpdatedEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.GroupUpdatedEvent;
  return proto.com.elarian.hera.proto.GroupUpdatedEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.GroupUpdatedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.GroupUpdatedEvent}
 */
proto.com.elarian.hera.proto.GroupUpdatedEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setHumanId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrgId(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 4:
      var value = new common_model_pb.AppConnectionProps;
      reader.readMessage(value,common_model_pb.AppConnectionProps.deserializeBinaryFromReader);
      msg.setCxnProps(value);
      break;
    case 5:
      var value = new common_model_pb.GroupIndex;
      reader.readMessage(value,common_model_pb.GroupIndex.deserializeBinaryFromReader);
      msg.addUpdates(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.GroupUpdatedEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.GroupUpdatedEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.GroupUpdatedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.GroupUpdatedEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHumanId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOrgId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCxnProps();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      common_model_pb.AppConnectionProps.serializeBinaryToWriter
    );
  }
  f = message.getUpdatesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      common_model_pb.GroupIndex.serializeBinaryToWriter
    );
  }
};


/**
 * optional string human_id = 1;
 * @return {string}
 */
proto.com.elarian.hera.proto.GroupUpdatedEvent.prototype.getHumanId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.GroupUpdatedEvent} returns this
 */
proto.com.elarian.hera.proto.GroupUpdatedEvent.prototype.setHumanId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string org_id = 2;
 * @return {string}
 */
proto.com.elarian.hera.proto.GroupUpdatedEvent.prototype.getOrgId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.GroupUpdatedEvent} returns this
 */
proto.com.elarian.hera.proto.GroupUpdatedEvent.prototype.setOrgId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.Timestamp timestamp = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.com.elarian.hera.proto.GroupUpdatedEvent.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.com.elarian.hera.proto.GroupUpdatedEvent} returns this
*/
proto.com.elarian.hera.proto.GroupUpdatedEvent.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.GroupUpdatedEvent} returns this
 */
proto.com.elarian.hera.proto.GroupUpdatedEvent.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.GroupUpdatedEvent.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional AppConnectionProps cxn_props = 4;
 * @return {?proto.com.elarian.hera.proto.AppConnectionProps}
 */
proto.com.elarian.hera.proto.GroupUpdatedEvent.prototype.getCxnProps = function() {
  return /** @type{?proto.com.elarian.hera.proto.AppConnectionProps} */ (
    jspb.Message.getWrapperField(this, common_model_pb.AppConnectionProps, 4));
};


/**
 * @param {?proto.com.elarian.hera.proto.AppConnectionProps|undefined} value
 * @return {!proto.com.elarian.hera.proto.GroupUpdatedEvent} returns this
*/
proto.com.elarian.hera.proto.GroupUpdatedEvent.prototype.setCxnProps = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.GroupUpdatedEvent} returns this
 */
proto.com.elarian.hera.proto.GroupUpdatedEvent.prototype.clearCxnProps = function() {
  return this.setCxnProps(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.GroupUpdatedEvent.prototype.hasCxnProps = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated GroupIndex updates = 5;
 * @return {!Array<!proto.com.elarian.hera.proto.GroupIndex>}
 */
proto.com.elarian.hera.proto.GroupUpdatedEvent.prototype.getUpdatesList = function() {
  return /** @type{!Array<!proto.com.elarian.hera.proto.GroupIndex>} */ (
    jspb.Message.getRepeatedWrapperField(this, common_model_pb.GroupIndex, 5));
};


/**
 * @param {!Array<!proto.com.elarian.hera.proto.GroupIndex>} value
 * @return {!proto.com.elarian.hera.proto.GroupUpdatedEvent} returns this
*/
proto.com.elarian.hera.proto.GroupUpdatedEvent.prototype.setUpdatesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.com.elarian.hera.proto.GroupIndex=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.elarian.hera.proto.GroupIndex}
 */
proto.com.elarian.hera.proto.GroupUpdatedEvent.prototype.addUpdates = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.com.elarian.hera.proto.GroupIndex, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.elarian.hera.proto.GroupUpdatedEvent} returns this
 */
proto.com.elarian.hera.proto.GroupUpdatedEvent.prototype.clearUpdatesList = function() {
  return this.setUpdatesList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.elarian.hera.proto.GroupDeletedEvent.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.GroupDeletedEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.GroupDeletedEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.GroupDeletedEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.GroupDeletedEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    humanId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    orgId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    cxnProps: (f = msg.getCxnProps()) && common_model_pb.AppConnectionProps.toObject(includeInstance, f),
    deletionsList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.GroupDeletedEvent}
 */
proto.com.elarian.hera.proto.GroupDeletedEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.GroupDeletedEvent;
  return proto.com.elarian.hera.proto.GroupDeletedEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.GroupDeletedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.GroupDeletedEvent}
 */
proto.com.elarian.hera.proto.GroupDeletedEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setHumanId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrgId(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 4:
      var value = new common_model_pb.AppConnectionProps;
      reader.readMessage(value,common_model_pb.AppConnectionProps.deserializeBinaryFromReader);
      msg.setCxnProps(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addDeletions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.GroupDeletedEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.GroupDeletedEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.GroupDeletedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.GroupDeletedEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHumanId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOrgId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCxnProps();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      common_model_pb.AppConnectionProps.serializeBinaryToWriter
    );
  }
  f = message.getDeletionsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
};


/**
 * optional string human_id = 1;
 * @return {string}
 */
proto.com.elarian.hera.proto.GroupDeletedEvent.prototype.getHumanId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.GroupDeletedEvent} returns this
 */
proto.com.elarian.hera.proto.GroupDeletedEvent.prototype.setHumanId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string org_id = 2;
 * @return {string}
 */
proto.com.elarian.hera.proto.GroupDeletedEvent.prototype.getOrgId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.GroupDeletedEvent} returns this
 */
proto.com.elarian.hera.proto.GroupDeletedEvent.prototype.setOrgId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.Timestamp timestamp = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.com.elarian.hera.proto.GroupDeletedEvent.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.com.elarian.hera.proto.GroupDeletedEvent} returns this
*/
proto.com.elarian.hera.proto.GroupDeletedEvent.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.GroupDeletedEvent} returns this
 */
proto.com.elarian.hera.proto.GroupDeletedEvent.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.GroupDeletedEvent.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional AppConnectionProps cxn_props = 4;
 * @return {?proto.com.elarian.hera.proto.AppConnectionProps}
 */
proto.com.elarian.hera.proto.GroupDeletedEvent.prototype.getCxnProps = function() {
  return /** @type{?proto.com.elarian.hera.proto.AppConnectionProps} */ (
    jspb.Message.getWrapperField(this, common_model_pb.AppConnectionProps, 4));
};


/**
 * @param {?proto.com.elarian.hera.proto.AppConnectionProps|undefined} value
 * @return {!proto.com.elarian.hera.proto.GroupDeletedEvent} returns this
*/
proto.com.elarian.hera.proto.GroupDeletedEvent.prototype.setCxnProps = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.GroupDeletedEvent} returns this
 */
proto.com.elarian.hera.proto.GroupDeletedEvent.prototype.clearCxnProps = function() {
  return this.setCxnProps(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.GroupDeletedEvent.prototype.hasCxnProps = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated string deletions = 5;
 * @return {!Array<string>}
 */
proto.com.elarian.hera.proto.GroupDeletedEvent.prototype.getDeletionsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.com.elarian.hera.proto.GroupDeletedEvent} returns this
 */
proto.com.elarian.hera.proto.GroupDeletedEvent.prototype.setDeletionsList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.com.elarian.hera.proto.GroupDeletedEvent} returns this
 */
proto.com.elarian.hera.proto.GroupDeletedEvent.prototype.addDeletions = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.elarian.hera.proto.GroupDeletedEvent} returns this
 */
proto.com.elarian.hera.proto.GroupDeletedEvent.prototype.clearDeletionsList = function() {
  return this.setDeletionsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.MetadataUpdatedEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.MetadataUpdatedEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.MetadataUpdatedEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.MetadataUpdatedEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    humanId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    orgId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    cxnProps: (f = msg.getCxnProps()) && common_model_pb.AppConnectionProps.toObject(includeInstance, f),
    updatesMap: (f = msg.getUpdatesMap()) ? f.toObject(includeInstance, proto.com.elarian.hera.proto.DataMapValue.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.MetadataUpdatedEvent}
 */
proto.com.elarian.hera.proto.MetadataUpdatedEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.MetadataUpdatedEvent;
  return proto.com.elarian.hera.proto.MetadataUpdatedEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.MetadataUpdatedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.MetadataUpdatedEvent}
 */
proto.com.elarian.hera.proto.MetadataUpdatedEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setHumanId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrgId(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 4:
      var value = new common_model_pb.AppConnectionProps;
      reader.readMessage(value,common_model_pb.AppConnectionProps.deserializeBinaryFromReader);
      msg.setCxnProps(value);
      break;
    case 5:
      var value = msg.getUpdatesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.com.elarian.hera.proto.DataMapValue.deserializeBinaryFromReader, "", new proto.com.elarian.hera.proto.DataMapValue());
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.MetadataUpdatedEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.MetadataUpdatedEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.MetadataUpdatedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.MetadataUpdatedEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHumanId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOrgId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCxnProps();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      common_model_pb.AppConnectionProps.serializeBinaryToWriter
    );
  }
  f = message.getUpdatesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(5, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.com.elarian.hera.proto.DataMapValue.serializeBinaryToWriter);
  }
};


/**
 * optional string human_id = 1;
 * @return {string}
 */
proto.com.elarian.hera.proto.MetadataUpdatedEvent.prototype.getHumanId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.MetadataUpdatedEvent} returns this
 */
proto.com.elarian.hera.proto.MetadataUpdatedEvent.prototype.setHumanId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string org_id = 2;
 * @return {string}
 */
proto.com.elarian.hera.proto.MetadataUpdatedEvent.prototype.getOrgId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.MetadataUpdatedEvent} returns this
 */
proto.com.elarian.hera.proto.MetadataUpdatedEvent.prototype.setOrgId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.Timestamp timestamp = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.com.elarian.hera.proto.MetadataUpdatedEvent.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.com.elarian.hera.proto.MetadataUpdatedEvent} returns this
*/
proto.com.elarian.hera.proto.MetadataUpdatedEvent.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.MetadataUpdatedEvent} returns this
 */
proto.com.elarian.hera.proto.MetadataUpdatedEvent.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.MetadataUpdatedEvent.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional AppConnectionProps cxn_props = 4;
 * @return {?proto.com.elarian.hera.proto.AppConnectionProps}
 */
proto.com.elarian.hera.proto.MetadataUpdatedEvent.prototype.getCxnProps = function() {
  return /** @type{?proto.com.elarian.hera.proto.AppConnectionProps} */ (
    jspb.Message.getWrapperField(this, common_model_pb.AppConnectionProps, 4));
};


/**
 * @param {?proto.com.elarian.hera.proto.AppConnectionProps|undefined} value
 * @return {!proto.com.elarian.hera.proto.MetadataUpdatedEvent} returns this
*/
proto.com.elarian.hera.proto.MetadataUpdatedEvent.prototype.setCxnProps = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.MetadataUpdatedEvent} returns this
 */
proto.com.elarian.hera.proto.MetadataUpdatedEvent.prototype.clearCxnProps = function() {
  return this.setCxnProps(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.MetadataUpdatedEvent.prototype.hasCxnProps = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * map<string, DataMapValue> updates = 5;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.com.elarian.hera.proto.DataMapValue>}
 */
proto.com.elarian.hera.proto.MetadataUpdatedEvent.prototype.getUpdatesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.com.elarian.hera.proto.DataMapValue>} */ (
      jspb.Message.getMapField(this, 5, opt_noLazyCreate,
      proto.com.elarian.hera.proto.DataMapValue));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.elarian.hera.proto.MetadataUpdatedEvent} returns this
 */
proto.com.elarian.hera.proto.MetadataUpdatedEvent.prototype.clearUpdatesMap = function() {
  this.getUpdatesMap().clear();
  return this;};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.elarian.hera.proto.MetadataDeletedEvent.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.MetadataDeletedEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.MetadataDeletedEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.MetadataDeletedEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.MetadataDeletedEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    humanId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    orgId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    cxnProps: (f = msg.getCxnProps()) && common_model_pb.AppConnectionProps.toObject(includeInstance, f),
    deletionsList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.MetadataDeletedEvent}
 */
proto.com.elarian.hera.proto.MetadataDeletedEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.MetadataDeletedEvent;
  return proto.com.elarian.hera.proto.MetadataDeletedEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.MetadataDeletedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.MetadataDeletedEvent}
 */
proto.com.elarian.hera.proto.MetadataDeletedEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setHumanId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrgId(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 4:
      var value = new common_model_pb.AppConnectionProps;
      reader.readMessage(value,common_model_pb.AppConnectionProps.deserializeBinaryFromReader);
      msg.setCxnProps(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addDeletions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.MetadataDeletedEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.MetadataDeletedEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.MetadataDeletedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.MetadataDeletedEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHumanId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOrgId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCxnProps();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      common_model_pb.AppConnectionProps.serializeBinaryToWriter
    );
  }
  f = message.getDeletionsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
};


/**
 * optional string human_id = 1;
 * @return {string}
 */
proto.com.elarian.hera.proto.MetadataDeletedEvent.prototype.getHumanId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.MetadataDeletedEvent} returns this
 */
proto.com.elarian.hera.proto.MetadataDeletedEvent.prototype.setHumanId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string org_id = 2;
 * @return {string}
 */
proto.com.elarian.hera.proto.MetadataDeletedEvent.prototype.getOrgId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.MetadataDeletedEvent} returns this
 */
proto.com.elarian.hera.proto.MetadataDeletedEvent.prototype.setOrgId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.Timestamp timestamp = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.com.elarian.hera.proto.MetadataDeletedEvent.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.com.elarian.hera.proto.MetadataDeletedEvent} returns this
*/
proto.com.elarian.hera.proto.MetadataDeletedEvent.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.MetadataDeletedEvent} returns this
 */
proto.com.elarian.hera.proto.MetadataDeletedEvent.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.MetadataDeletedEvent.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional AppConnectionProps cxn_props = 4;
 * @return {?proto.com.elarian.hera.proto.AppConnectionProps}
 */
proto.com.elarian.hera.proto.MetadataDeletedEvent.prototype.getCxnProps = function() {
  return /** @type{?proto.com.elarian.hera.proto.AppConnectionProps} */ (
    jspb.Message.getWrapperField(this, common_model_pb.AppConnectionProps, 4));
};


/**
 * @param {?proto.com.elarian.hera.proto.AppConnectionProps|undefined} value
 * @return {!proto.com.elarian.hera.proto.MetadataDeletedEvent} returns this
*/
proto.com.elarian.hera.proto.MetadataDeletedEvent.prototype.setCxnProps = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.MetadataDeletedEvent} returns this
 */
proto.com.elarian.hera.proto.MetadataDeletedEvent.prototype.clearCxnProps = function() {
  return this.setCxnProps(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.MetadataDeletedEvent.prototype.hasCxnProps = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated string deletions = 5;
 * @return {!Array<string>}
 */
proto.com.elarian.hera.proto.MetadataDeletedEvent.prototype.getDeletionsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.com.elarian.hera.proto.MetadataDeletedEvent} returns this
 */
proto.com.elarian.hera.proto.MetadataDeletedEvent.prototype.setDeletionsList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.com.elarian.hera.proto.MetadataDeletedEvent} returns this
 */
proto.com.elarian.hera.proto.MetadataDeletedEvent.prototype.addDeletions = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.elarian.hera.proto.MetadataDeletedEvent} returns this
 */
proto.com.elarian.hera.proto.MetadataDeletedEvent.prototype.clearDeletionsList = function() {
  return this.setDeletionsList([]);
};


goog.object.extend(exports, proto.com.elarian.hera.proto);
