/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.com.elarian.hera.proto.MessageDeliveryStatus');

/**
 * @enum {number}
 */
proto.com.elarian.hera.proto.MessageDeliveryStatus = {
  MESSAGE_DELIVERY_STATUS_UNSEPCIFIED: 0,
  MESSAGE_DELIVERY_STATUS_SENT: 101,
  MESSAGE_DELIVERY_STATUS_DELIVERED: 300,
  MESSAGE_DELIVERY_STATUS_READ: 301,
  MESSAGE_DELIVERY_STATUS_RECEIVED: 302,
  MESSAGE_DELIVERY_STATUS_FAILED: 400,
  MESSAGE_DELIVERY_STATUS_NO_CONSENT: 401,
  MESSAGE_DELIVERY_STATUS_NO_CAPABILITY: 402,
  MESSAGE_DELIVERY_STATUS_EXPIRED: 403,
  MESSAGE_DELIVERY_STATUS_ONLY_TEMPLATE_ALLOWED: 404,
  MESSAGE_DELIVERY_STATUS_INVALID_CHANNEL_NUMBER: 405,
  MESSAGE_DELIVERY_STATUS_NOT_SUPPORTED: 406,
  MESSAGE_DELIVERY_STATUS_INVALID_REPLY_TO_MESSAGE_ID: 407,
  MESSAGE_DELIVERY_STATUS_INVALID_CUSTOMER_ID: 408,
  MESSAGE_DELIVERY_STATUS_DUPLICATE_REQUEST: 409,
  MESSAGE_DELIVERY_STATUS_TAG_NOT_FOUND: 410,
  MESSAGE_DELIVERY_STATUS_CUSTOMER_NUMBER_NOT_FOUND: 411,
  MESSAGE_DELIVERY_STATUS_DECOMMISSIONED_CUSTOMERID: 412,
  MESSAGE_DELIVERY_STATUS_INVALID_REQUEST: 413,
  MESSAGE_DELIVERY_STATUS_APPLICATION_ERROR: 501
};

