/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.com.elarian.hera.proto.MessagingChannelStateEntry');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.com.elarian.hera.proto.CustomerNumber');
goog.require('proto.com.elarian.hera.proto.MessagingChannelNumber');
goog.require('proto.com.elarian.hera.proto.MessagingConsentStateEntry');
goog.require('proto.com.elarian.hera.proto.MessagingSessionStateEntry');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.MessagingChannelStateEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.elarian.hera.proto.MessagingChannelStateEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.elarian.hera.proto.MessagingChannelStateEntry.displayName = 'proto.com.elarian.hera.proto.MessagingChannelStateEntry';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.MessagingChannelStateEntry.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.MessagingChannelStateEntry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.MessagingChannelStateEntry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.MessagingChannelStateEntry.toObject = function(includeInstance, msg) {
  var f, obj = {
    customerNumber: (f = msg.getCustomerNumber()) && proto.com.elarian.hera.proto.CustomerNumber.toObject(includeInstance, f),
    channelNumber: (f = msg.getChannelNumber()) && proto.com.elarian.hera.proto.MessagingChannelNumber.toObject(includeInstance, f),
    consentState: (f = msg.getConsentState()) && proto.com.elarian.hera.proto.MessagingConsentStateEntry.toObject(includeInstance, f),
    activeSession: (f = msg.getActiveSession()) && proto.com.elarian.hera.proto.MessagingSessionStateEntry.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.MessagingChannelStateEntry}
 */
proto.com.elarian.hera.proto.MessagingChannelStateEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.MessagingChannelStateEntry;
  return proto.com.elarian.hera.proto.MessagingChannelStateEntry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.MessagingChannelStateEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.MessagingChannelStateEntry}
 */
proto.com.elarian.hera.proto.MessagingChannelStateEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.elarian.hera.proto.CustomerNumber;
      reader.readMessage(value,proto.com.elarian.hera.proto.CustomerNumber.deserializeBinaryFromReader);
      msg.setCustomerNumber(value);
      break;
    case 2:
      var value = new proto.com.elarian.hera.proto.MessagingChannelNumber;
      reader.readMessage(value,proto.com.elarian.hera.proto.MessagingChannelNumber.deserializeBinaryFromReader);
      msg.setChannelNumber(value);
      break;
    case 3:
      var value = new proto.com.elarian.hera.proto.MessagingConsentStateEntry;
      reader.readMessage(value,proto.com.elarian.hera.proto.MessagingConsentStateEntry.deserializeBinaryFromReader);
      msg.setConsentState(value);
      break;
    case 4:
      var value = new proto.com.elarian.hera.proto.MessagingSessionStateEntry;
      reader.readMessage(value,proto.com.elarian.hera.proto.MessagingSessionStateEntry.deserializeBinaryFromReader);
      msg.setActiveSession(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.MessagingChannelStateEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.MessagingChannelStateEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.MessagingChannelStateEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.MessagingChannelStateEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCustomerNumber();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.com.elarian.hera.proto.CustomerNumber.serializeBinaryToWriter
    );
  }
  f = message.getChannelNumber();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.com.elarian.hera.proto.MessagingChannelNumber.serializeBinaryToWriter
    );
  }
  f = message.getConsentState();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.com.elarian.hera.proto.MessagingConsentStateEntry.serializeBinaryToWriter
    );
  }
  f = message.getActiveSession();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.com.elarian.hera.proto.MessagingSessionStateEntry.serializeBinaryToWriter
    );
  }
};


/**
 * optional CustomerNumber customer_number = 1;
 * @return {?proto.com.elarian.hera.proto.CustomerNumber}
 */
proto.com.elarian.hera.proto.MessagingChannelStateEntry.prototype.getCustomerNumber = function() {
  return /** @type{?proto.com.elarian.hera.proto.CustomerNumber} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.CustomerNumber, 1));
};


/** @param {?proto.com.elarian.hera.proto.CustomerNumber|undefined} value */
proto.com.elarian.hera.proto.MessagingChannelStateEntry.prototype.setCustomerNumber = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.com.elarian.hera.proto.MessagingChannelStateEntry.prototype.clearCustomerNumber = function() {
  this.setCustomerNumber(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.MessagingChannelStateEntry.prototype.hasCustomerNumber = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional MessagingChannelNumber channel_number = 2;
 * @return {?proto.com.elarian.hera.proto.MessagingChannelNumber}
 */
proto.com.elarian.hera.proto.MessagingChannelStateEntry.prototype.getChannelNumber = function() {
  return /** @type{?proto.com.elarian.hera.proto.MessagingChannelNumber} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.MessagingChannelNumber, 2));
};


/** @param {?proto.com.elarian.hera.proto.MessagingChannelNumber|undefined} value */
proto.com.elarian.hera.proto.MessagingChannelStateEntry.prototype.setChannelNumber = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.com.elarian.hera.proto.MessagingChannelStateEntry.prototype.clearChannelNumber = function() {
  this.setChannelNumber(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.MessagingChannelStateEntry.prototype.hasChannelNumber = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional MessagingConsentStateEntry consent_state = 3;
 * @return {?proto.com.elarian.hera.proto.MessagingConsentStateEntry}
 */
proto.com.elarian.hera.proto.MessagingChannelStateEntry.prototype.getConsentState = function() {
  return /** @type{?proto.com.elarian.hera.proto.MessagingConsentStateEntry} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.MessagingConsentStateEntry, 3));
};


/** @param {?proto.com.elarian.hera.proto.MessagingConsentStateEntry|undefined} value */
proto.com.elarian.hera.proto.MessagingChannelStateEntry.prototype.setConsentState = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.com.elarian.hera.proto.MessagingChannelStateEntry.prototype.clearConsentState = function() {
  this.setConsentState(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.MessagingChannelStateEntry.prototype.hasConsentState = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional MessagingSessionStateEntry active_session = 4;
 * @return {?proto.com.elarian.hera.proto.MessagingSessionStateEntry}
 */
proto.com.elarian.hera.proto.MessagingChannelStateEntry.prototype.getActiveSession = function() {
  return /** @type{?proto.com.elarian.hera.proto.MessagingSessionStateEntry} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.MessagingSessionStateEntry, 4));
};


/** @param {?proto.com.elarian.hera.proto.MessagingSessionStateEntry|undefined} value */
proto.com.elarian.hera.proto.MessagingChannelStateEntry.prototype.setActiveSession = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.com.elarian.hera.proto.MessagingChannelStateEntry.prototype.clearActiveSession = function() {
  this.setActiveSession(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.MessagingChannelStateEntry.prototype.hasActiveSession = function() {
  return jspb.Message.getField(this, 4) != null;
};


