/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.com.elarian.hera.proto.MessageStateEntry');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.com.elarian.hera.proto.CustomerNumber');
goog.require('proto.com.elarian.hera.proto.LocationMessageBody');
goog.require('proto.com.elarian.hera.proto.MediaMessageBody');
goog.require('proto.com.elarian.hera.proto.MessagingChannelNumber');
goog.require('proto.com.elarian.hera.proto.TextMessageTemplate');
goog.require('proto.google.protobuf.StringValue');
goog.require('proto.google.protobuf.Timestamp');

goog.forwardDeclare('proto.com.elarian.hera.proto.CustomerEventDirection');
goog.forwardDeclare('proto.com.elarian.hera.proto.MessageDeliveryStatus');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.MessageStateEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.elarian.hera.proto.MessageStateEntry.repeatedFields_, null);
};
goog.inherits(proto.com.elarian.hera.proto.MessageStateEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.elarian.hera.proto.MessageStateEntry.displayName = 'proto.com.elarian.hera.proto.MessageStateEntry';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.elarian.hera.proto.MessageStateEntry.repeatedFields_ = [8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.MessageStateEntry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.MessageStateEntry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.MessageStateEntry.toObject = function(includeInstance, msg) {
  var f, obj = {
    direction: jspb.Message.getFieldWithDefault(msg, 1, 0),
    customerNumber: (f = msg.getCustomerNumber()) && proto.com.elarian.hera.proto.CustomerNumber.toObject(includeInstance, f),
    channelNumber: (f = msg.getChannelNumber()) && proto.com.elarian.hera.proto.MessagingChannelNumber.toObject(includeInstance, f),
    messageId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    productId: jspb.Message.getFieldWithDefault(msg, 5, ""),
    text: (f = msg.getText()) && proto.google.protobuf.StringValue.toObject(includeInstance, f),
    template: (f = msg.getTemplate()) && proto.com.elarian.hera.proto.TextMessageTemplate.toObject(includeInstance, f),
    mediaList: jspb.Message.toObjectList(msg.getMediaList(),
    proto.com.elarian.hera.proto.MediaMessageBody.toObject, includeInstance),
    location: (f = msg.getLocation()) && proto.com.elarian.hera.proto.LocationMessageBody.toObject(includeInstance, f),
    createdAt: (f = msg.getCreatedAt()) && proto.google.protobuf.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && proto.google.protobuf.Timestamp.toObject(includeInstance, f),
    status: jspb.Message.getFieldWithDefault(msg, 12, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.MessageStateEntry}
 */
proto.com.elarian.hera.proto.MessageStateEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.MessageStateEntry;
  return proto.com.elarian.hera.proto.MessageStateEntry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.MessageStateEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.MessageStateEntry}
 */
proto.com.elarian.hera.proto.MessageStateEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.com.elarian.hera.proto.CustomerEventDirection} */ (reader.readEnum());
      msg.setDirection(value);
      break;
    case 2:
      var value = new proto.com.elarian.hera.proto.CustomerNumber;
      reader.readMessage(value,proto.com.elarian.hera.proto.CustomerNumber.deserializeBinaryFromReader);
      msg.setCustomerNumber(value);
      break;
    case 3:
      var value = new proto.com.elarian.hera.proto.MessagingChannelNumber;
      reader.readMessage(value,proto.com.elarian.hera.proto.MessagingChannelNumber.deserializeBinaryFromReader);
      msg.setChannelNumber(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessageId(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setProductId(value);
      break;
    case 6:
      var value = new proto.google.protobuf.StringValue;
      reader.readMessage(value,proto.google.protobuf.StringValue.deserializeBinaryFromReader);
      msg.setText(value);
      break;
    case 7:
      var value = new proto.com.elarian.hera.proto.TextMessageTemplate;
      reader.readMessage(value,proto.com.elarian.hera.proto.TextMessageTemplate.deserializeBinaryFromReader);
      msg.setTemplate(value);
      break;
    case 8:
      var value = new proto.com.elarian.hera.proto.MediaMessageBody;
      reader.readMessage(value,proto.com.elarian.hera.proto.MediaMessageBody.deserializeBinaryFromReader);
      msg.addMedia(value);
      break;
    case 9:
      var value = new proto.com.elarian.hera.proto.LocationMessageBody;
      reader.readMessage(value,proto.com.elarian.hera.proto.LocationMessageBody.deserializeBinaryFromReader);
      msg.setLocation(value);
      break;
    case 10:
      var value = new proto.google.protobuf.Timestamp;
      reader.readMessage(value,proto.google.protobuf.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 11:
      var value = new proto.google.protobuf.Timestamp;
      reader.readMessage(value,proto.google.protobuf.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    case 12:
      var value = /** @type {!proto.com.elarian.hera.proto.MessageDeliveryStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.MessageStateEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.MessageStateEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.MessageStateEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDirection();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getCustomerNumber();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.com.elarian.hera.proto.CustomerNumber.serializeBinaryToWriter
    );
  }
  f = message.getChannelNumber();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.com.elarian.hera.proto.MessagingChannelNumber.serializeBinaryToWriter
    );
  }
  f = message.getMessageId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getProductId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getText();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.google.protobuf.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getTemplate();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.com.elarian.hera.proto.TextMessageTemplate.serializeBinaryToWriter
    );
  }
  f = message.getMediaList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      proto.com.elarian.hera.proto.MediaMessageBody.serializeBinaryToWriter
    );
  }
  f = message.getLocation();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.com.elarian.hera.proto.LocationMessageBody.serializeBinaryToWriter
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.google.protobuf.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.google.protobuf.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      12,
      f
    );
  }
};


/**
 * optional CustomerEventDirection direction = 1;
 * @return {!proto.com.elarian.hera.proto.CustomerEventDirection}
 */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.getDirection = function() {
  return /** @type {!proto.com.elarian.hera.proto.CustomerEventDirection} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.com.elarian.hera.proto.CustomerEventDirection} value */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.setDirection = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional CustomerNumber customer_number = 2;
 * @return {?proto.com.elarian.hera.proto.CustomerNumber}
 */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.getCustomerNumber = function() {
  return /** @type{?proto.com.elarian.hera.proto.CustomerNumber} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.CustomerNumber, 2));
};


/** @param {?proto.com.elarian.hera.proto.CustomerNumber|undefined} value */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.setCustomerNumber = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.com.elarian.hera.proto.MessageStateEntry.prototype.clearCustomerNumber = function() {
  this.setCustomerNumber(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.hasCustomerNumber = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional MessagingChannelNumber channel_number = 3;
 * @return {?proto.com.elarian.hera.proto.MessagingChannelNumber}
 */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.getChannelNumber = function() {
  return /** @type{?proto.com.elarian.hera.proto.MessagingChannelNumber} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.MessagingChannelNumber, 3));
};


/** @param {?proto.com.elarian.hera.proto.MessagingChannelNumber|undefined} value */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.setChannelNumber = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.com.elarian.hera.proto.MessageStateEntry.prototype.clearChannelNumber = function() {
  this.setChannelNumber(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.hasChannelNumber = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string message_id = 4;
 * @return {string}
 */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.getMessageId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.setMessageId = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string product_id = 5;
 * @return {string}
 */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.getProductId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.setProductId = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional google.protobuf.StringValue text = 6;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.getText = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.StringValue, 6));
};


/** @param {?proto.google.protobuf.StringValue|undefined} value */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.setText = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.com.elarian.hera.proto.MessageStateEntry.prototype.clearText = function() {
  this.setText(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.hasText = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional TextMessageTemplate template = 7;
 * @return {?proto.com.elarian.hera.proto.TextMessageTemplate}
 */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.getTemplate = function() {
  return /** @type{?proto.com.elarian.hera.proto.TextMessageTemplate} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.TextMessageTemplate, 7));
};


/** @param {?proto.com.elarian.hera.proto.TextMessageTemplate|undefined} value */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.setTemplate = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.com.elarian.hera.proto.MessageStateEntry.prototype.clearTemplate = function() {
  this.setTemplate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.hasTemplate = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * repeated MediaMessageBody media = 8;
 * @return {!Array.<!proto.com.elarian.hera.proto.MediaMessageBody>}
 */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.getMediaList = function() {
  return /** @type{!Array.<!proto.com.elarian.hera.proto.MediaMessageBody>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.elarian.hera.proto.MediaMessageBody, 8));
};


/** @param {!Array.<!proto.com.elarian.hera.proto.MediaMessageBody>} value */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.setMediaList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.com.elarian.hera.proto.MediaMessageBody=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.elarian.hera.proto.MediaMessageBody}
 */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.addMedia = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.com.elarian.hera.proto.MediaMessageBody, opt_index);
};


proto.com.elarian.hera.proto.MessageStateEntry.prototype.clearMediaList = function() {
  this.setMediaList([]);
};


/**
 * optional LocationMessageBody location = 9;
 * @return {?proto.com.elarian.hera.proto.LocationMessageBody}
 */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.getLocation = function() {
  return /** @type{?proto.com.elarian.hera.proto.LocationMessageBody} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.LocationMessageBody, 9));
};


/** @param {?proto.com.elarian.hera.proto.LocationMessageBody|undefined} value */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.setLocation = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.com.elarian.hera.proto.MessageStateEntry.prototype.clearLocation = function() {
  this.setLocation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.hasLocation = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional google.protobuf.Timestamp created_at = 10;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Timestamp, 10));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.setCreatedAt = function(value) {
  jspb.Message.setWrapperField(this, 10, value);
};


proto.com.elarian.hera.proto.MessageStateEntry.prototype.clearCreatedAt = function() {
  this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 11;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Timestamp, 11));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.setUpdatedAt = function(value) {
  jspb.Message.setWrapperField(this, 11, value);
};


proto.com.elarian.hera.proto.MessageStateEntry.prototype.clearUpdatedAt = function() {
  this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional MessageDeliveryStatus status = 12;
 * @return {!proto.com.elarian.hera.proto.MessageDeliveryStatus}
 */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.getStatus = function() {
  return /** @type {!proto.com.elarian.hera.proto.MessageDeliveryStatus} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/** @param {!proto.com.elarian.hera.proto.MessageDeliveryStatus} value */
proto.com.elarian.hera.proto.MessageStateEntry.prototype.setStatus = function(value) {
  jspb.Message.setField(this, 12, value);
};


