/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.com.elarian.hera.proto.PaymentStatus');

/**
 * @enum {number}
 */
proto.com.elarian.hera.proto.PaymentStatus = {
  PAYMENT_STATUS_UNSPECIFIED: 0,
  PAYMENT_STATUS_QUEUED: 101,
  PAYMENT_STATUS_PENDING_CONFIRMATION: 102,
  PAYMENT_STATUS_PENDING_VALIDATION: 103,
  PAYMENT_STATUS_VALIDATED: 104,
  PAYMENT_STATUS_INVALID_REQUEST: 200,
  PAYMENT_STATUS_NOT_SUPPORTED: 201,
  PAYMENT_STATUS_INSUFFICIENT_FUNDS: 202,
  PAYMENT_STATUS_APPLICATION_ERROR: 203,
  PAYMENT_STATUS_NOT_ALLOWED: 204,
  PAYMENT_STATUS_DUPLICATE_REQUEST: 205,
  PAYMENT_STATUS_INVALID_WALLET: 206,
  PAYMENT_STATUS_DECOMMISSIONED_CUSTOMER_ID: 299,
  PAYMENT_STATUS_SUCCESS: 300,
  PAYMENT_STATUS_PASS_THROUGH: 301,
  PAYMENT_STATUS_FAILED: 400,
  PAYMENT_STATUS_THROTTLED: 401,
  PAYMENT_STATUS_EXPIRED: 402,
  PAYMENT_STATUS_REJECTED: 403,
  PAYMENT_STATUS_REVERSED: 500
};

