// source: purse.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var common_pb = require('./common_pb.js');
goog.object.extend(proto, common_pb);
goog.exportSymbol('proto.com.elarian.hera.proto.CurrencyUpdatedEvent', null, global);
goog.exportSymbol('proto.com.elarian.hera.proto.DepositCompletedEvent', null, global);
goog.exportSymbol('proto.com.elarian.hera.proto.PurseEvent', null, global);
goog.exportSymbol('proto.com.elarian.hera.proto.PurseEvent.EventCase', null, global);
goog.exportSymbol('proto.com.elarian.hera.proto.WithdrawalCompletedEvent', null, global);
goog.exportSymbol('proto.com.elarian.hera.proto.WithdrawalInitiatedEvent', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.PurseEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.com.elarian.hera.proto.PurseEvent.oneofGroups_);
};
goog.inherits(proto.com.elarian.hera.proto.PurseEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.elarian.hera.proto.PurseEvent.displayName = 'proto.com.elarian.hera.proto.PurseEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.CurrencyUpdatedEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.elarian.hera.proto.CurrencyUpdatedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.elarian.hera.proto.CurrencyUpdatedEvent.displayName = 'proto.com.elarian.hera.proto.CurrencyUpdatedEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.DepositCompletedEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.elarian.hera.proto.DepositCompletedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.elarian.hera.proto.DepositCompletedEvent.displayName = 'proto.com.elarian.hera.proto.DepositCompletedEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.elarian.hera.proto.WithdrawalInitiatedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.displayName = 'proto.com.elarian.hera.proto.WithdrawalInitiatedEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.elarian.hera.proto.WithdrawalCompletedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.elarian.hera.proto.WithdrawalCompletedEvent.displayName = 'proto.com.elarian.hera.proto.WithdrawalCompletedEvent';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.com.elarian.hera.proto.PurseEvent.oneofGroups_ = [[1,2,3,4]];

/**
 * @enum {number}
 */
proto.com.elarian.hera.proto.PurseEvent.EventCase = {
  EVENT_NOT_SET: 0,
  CURRENCY_UPDATED: 1,
  DEPOSIT_COMPLETED: 2,
  WITHDRAWAL_INITIATED: 3,
  WITHDRAWAL_COMPLETED: 4
};

/**
 * @return {proto.com.elarian.hera.proto.PurseEvent.EventCase}
 */
proto.com.elarian.hera.proto.PurseEvent.prototype.getEventCase = function() {
  return /** @type {proto.com.elarian.hera.proto.PurseEvent.EventCase} */(jspb.Message.computeOneofCase(this, proto.com.elarian.hera.proto.PurseEvent.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.PurseEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.PurseEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.PurseEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.PurseEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    currencyUpdated: (f = msg.getCurrencyUpdated()) && proto.com.elarian.hera.proto.CurrencyUpdatedEvent.toObject(includeInstance, f),
    depositCompleted: (f = msg.getDepositCompleted()) && proto.com.elarian.hera.proto.DepositCompletedEvent.toObject(includeInstance, f),
    withdrawalInitiated: (f = msg.getWithdrawalInitiated()) && proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.toObject(includeInstance, f),
    withdrawalCompleted: (f = msg.getWithdrawalCompleted()) && proto.com.elarian.hera.proto.WithdrawalCompletedEvent.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.PurseEvent}
 */
proto.com.elarian.hera.proto.PurseEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.PurseEvent;
  return proto.com.elarian.hera.proto.PurseEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.PurseEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.PurseEvent}
 */
proto.com.elarian.hera.proto.PurseEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.elarian.hera.proto.CurrencyUpdatedEvent;
      reader.readMessage(value,proto.com.elarian.hera.proto.CurrencyUpdatedEvent.deserializeBinaryFromReader);
      msg.setCurrencyUpdated(value);
      break;
    case 2:
      var value = new proto.com.elarian.hera.proto.DepositCompletedEvent;
      reader.readMessage(value,proto.com.elarian.hera.proto.DepositCompletedEvent.deserializeBinaryFromReader);
      msg.setDepositCompleted(value);
      break;
    case 3:
      var value = new proto.com.elarian.hera.proto.WithdrawalInitiatedEvent;
      reader.readMessage(value,proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.deserializeBinaryFromReader);
      msg.setWithdrawalInitiated(value);
      break;
    case 4:
      var value = new proto.com.elarian.hera.proto.WithdrawalCompletedEvent;
      reader.readMessage(value,proto.com.elarian.hera.proto.WithdrawalCompletedEvent.deserializeBinaryFromReader);
      msg.setWithdrawalCompleted(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.PurseEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.PurseEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.PurseEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.PurseEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCurrencyUpdated();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.com.elarian.hera.proto.CurrencyUpdatedEvent.serializeBinaryToWriter
    );
  }
  f = message.getDepositCompleted();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.com.elarian.hera.proto.DepositCompletedEvent.serializeBinaryToWriter
    );
  }
  f = message.getWithdrawalInitiated();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.serializeBinaryToWriter
    );
  }
  f = message.getWithdrawalCompleted();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.com.elarian.hera.proto.WithdrawalCompletedEvent.serializeBinaryToWriter
    );
  }
};


/**
 * optional CurrencyUpdatedEvent currency_updated = 1;
 * @return {?proto.com.elarian.hera.proto.CurrencyUpdatedEvent}
 */
proto.com.elarian.hera.proto.PurseEvent.prototype.getCurrencyUpdated = function() {
  return /** @type{?proto.com.elarian.hera.proto.CurrencyUpdatedEvent} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.CurrencyUpdatedEvent, 1));
};


/**
 * @param {?proto.com.elarian.hera.proto.CurrencyUpdatedEvent|undefined} value
 * @return {!proto.com.elarian.hera.proto.PurseEvent} returns this
*/
proto.com.elarian.hera.proto.PurseEvent.prototype.setCurrencyUpdated = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.com.elarian.hera.proto.PurseEvent.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.PurseEvent} returns this
 */
proto.com.elarian.hera.proto.PurseEvent.prototype.clearCurrencyUpdated = function() {
  return this.setCurrencyUpdated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.PurseEvent.prototype.hasCurrencyUpdated = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional DepositCompletedEvent deposit_completed = 2;
 * @return {?proto.com.elarian.hera.proto.DepositCompletedEvent}
 */
proto.com.elarian.hera.proto.PurseEvent.prototype.getDepositCompleted = function() {
  return /** @type{?proto.com.elarian.hera.proto.DepositCompletedEvent} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.DepositCompletedEvent, 2));
};


/**
 * @param {?proto.com.elarian.hera.proto.DepositCompletedEvent|undefined} value
 * @return {!proto.com.elarian.hera.proto.PurseEvent} returns this
*/
proto.com.elarian.hera.proto.PurseEvent.prototype.setDepositCompleted = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.com.elarian.hera.proto.PurseEvent.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.PurseEvent} returns this
 */
proto.com.elarian.hera.proto.PurseEvent.prototype.clearDepositCompleted = function() {
  return this.setDepositCompleted(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.PurseEvent.prototype.hasDepositCompleted = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional WithdrawalInitiatedEvent withdrawal_initiated = 3;
 * @return {?proto.com.elarian.hera.proto.WithdrawalInitiatedEvent}
 */
proto.com.elarian.hera.proto.PurseEvent.prototype.getWithdrawalInitiated = function() {
  return /** @type{?proto.com.elarian.hera.proto.WithdrawalInitiatedEvent} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.WithdrawalInitiatedEvent, 3));
};


/**
 * @param {?proto.com.elarian.hera.proto.WithdrawalInitiatedEvent|undefined} value
 * @return {!proto.com.elarian.hera.proto.PurseEvent} returns this
*/
proto.com.elarian.hera.proto.PurseEvent.prototype.setWithdrawalInitiated = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.com.elarian.hera.proto.PurseEvent.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.PurseEvent} returns this
 */
proto.com.elarian.hera.proto.PurseEvent.prototype.clearWithdrawalInitiated = function() {
  return this.setWithdrawalInitiated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.PurseEvent.prototype.hasWithdrawalInitiated = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional WithdrawalCompletedEvent withdrawal_completed = 4;
 * @return {?proto.com.elarian.hera.proto.WithdrawalCompletedEvent}
 */
proto.com.elarian.hera.proto.PurseEvent.prototype.getWithdrawalCompleted = function() {
  return /** @type{?proto.com.elarian.hera.proto.WithdrawalCompletedEvent} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.WithdrawalCompletedEvent, 4));
};


/**
 * @param {?proto.com.elarian.hera.proto.WithdrawalCompletedEvent|undefined} value
 * @return {!proto.com.elarian.hera.proto.PurseEvent} returns this
*/
proto.com.elarian.hera.proto.PurseEvent.prototype.setWithdrawalCompleted = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.com.elarian.hera.proto.PurseEvent.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.PurseEvent} returns this
 */
proto.com.elarian.hera.proto.PurseEvent.prototype.clearWithdrawalCompleted = function() {
  return this.setWithdrawalCompleted(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.PurseEvent.prototype.hasWithdrawalCompleted = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.CurrencyUpdatedEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.CurrencyUpdatedEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.CurrencyUpdatedEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.CurrencyUpdatedEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    orgId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    purseId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    cxnProps: (f = msg.getCxnProps()) && common_pb.AppConnectionProps.toObject(includeInstance, f),
    newBalance: (f = msg.getNewBalance()) && common_pb.PaymentBalance.toObject(includeInstance, f),
    transactionId: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.CurrencyUpdatedEvent}
 */
proto.com.elarian.hera.proto.CurrencyUpdatedEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.CurrencyUpdatedEvent;
  return proto.com.elarian.hera.proto.CurrencyUpdatedEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.CurrencyUpdatedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.CurrencyUpdatedEvent}
 */
proto.com.elarian.hera.proto.CurrencyUpdatedEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrgId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPurseId(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 4:
      var value = new common_pb.AppConnectionProps;
      reader.readMessage(value,common_pb.AppConnectionProps.deserializeBinaryFromReader);
      msg.setCxnProps(value);
      break;
    case 5:
      var value = new common_pb.PaymentBalance;
      reader.readMessage(value,common_pb.PaymentBalance.deserializeBinaryFromReader);
      msg.setNewBalance(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setTransactionId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.CurrencyUpdatedEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.CurrencyUpdatedEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.CurrencyUpdatedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.CurrencyUpdatedEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrgId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPurseId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCxnProps();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      common_pb.AppConnectionProps.serializeBinaryToWriter
    );
  }
  f = message.getNewBalance();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      common_pb.PaymentBalance.serializeBinaryToWriter
    );
  }
  f = message.getTransactionId();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string org_id = 1;
 * @return {string}
 */
proto.com.elarian.hera.proto.CurrencyUpdatedEvent.prototype.getOrgId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.CurrencyUpdatedEvent} returns this
 */
proto.com.elarian.hera.proto.CurrencyUpdatedEvent.prototype.setOrgId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string purse_id = 2;
 * @return {string}
 */
proto.com.elarian.hera.proto.CurrencyUpdatedEvent.prototype.getPurseId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.CurrencyUpdatedEvent} returns this
 */
proto.com.elarian.hera.proto.CurrencyUpdatedEvent.prototype.setPurseId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.Timestamp timestamp = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.com.elarian.hera.proto.CurrencyUpdatedEvent.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.com.elarian.hera.proto.CurrencyUpdatedEvent} returns this
*/
proto.com.elarian.hera.proto.CurrencyUpdatedEvent.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.CurrencyUpdatedEvent} returns this
 */
proto.com.elarian.hera.proto.CurrencyUpdatedEvent.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.CurrencyUpdatedEvent.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional AppConnectionProps cxn_props = 4;
 * @return {?proto.com.elarian.hera.proto.AppConnectionProps}
 */
proto.com.elarian.hera.proto.CurrencyUpdatedEvent.prototype.getCxnProps = function() {
  return /** @type{?proto.com.elarian.hera.proto.AppConnectionProps} */ (
    jspb.Message.getWrapperField(this, common_pb.AppConnectionProps, 4));
};


/**
 * @param {?proto.com.elarian.hera.proto.AppConnectionProps|undefined} value
 * @return {!proto.com.elarian.hera.proto.CurrencyUpdatedEvent} returns this
*/
proto.com.elarian.hera.proto.CurrencyUpdatedEvent.prototype.setCxnProps = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.CurrencyUpdatedEvent} returns this
 */
proto.com.elarian.hera.proto.CurrencyUpdatedEvent.prototype.clearCxnProps = function() {
  return this.setCxnProps(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.CurrencyUpdatedEvent.prototype.hasCxnProps = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional PaymentBalance new_balance = 5;
 * @return {?proto.com.elarian.hera.proto.PaymentBalance}
 */
proto.com.elarian.hera.proto.CurrencyUpdatedEvent.prototype.getNewBalance = function() {
  return /** @type{?proto.com.elarian.hera.proto.PaymentBalance} */ (
    jspb.Message.getWrapperField(this, common_pb.PaymentBalance, 5));
};


/**
 * @param {?proto.com.elarian.hera.proto.PaymentBalance|undefined} value
 * @return {!proto.com.elarian.hera.proto.CurrencyUpdatedEvent} returns this
*/
proto.com.elarian.hera.proto.CurrencyUpdatedEvent.prototype.setNewBalance = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.CurrencyUpdatedEvent} returns this
 */
proto.com.elarian.hera.proto.CurrencyUpdatedEvent.prototype.clearNewBalance = function() {
  return this.setNewBalance(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.CurrencyUpdatedEvent.prototype.hasNewBalance = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string transaction_id = 6;
 * @return {string}
 */
proto.com.elarian.hera.proto.CurrencyUpdatedEvent.prototype.getTransactionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.CurrencyUpdatedEvent} returns this
 */
proto.com.elarian.hera.proto.CurrencyUpdatedEvent.prototype.setTransactionId = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.DepositCompletedEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.DepositCompletedEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    orgId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    purseId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    cxnProps: (f = msg.getCxnProps()) && common_pb.AppConnectionProps.toObject(includeInstance, f),
    newBalance: (f = msg.getNewBalance()) && common_pb.PaymentBalance.toObject(includeInstance, f),
    transactionId: jspb.Message.getFieldWithDefault(msg, 6, ""),
    value: (f = msg.getValue()) && common_pb.Cash.toObject(includeInstance, f),
    narration: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.DepositCompletedEvent}
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.DepositCompletedEvent;
  return proto.com.elarian.hera.proto.DepositCompletedEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.DepositCompletedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.DepositCompletedEvent}
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrgId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPurseId(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 4:
      var value = new common_pb.AppConnectionProps;
      reader.readMessage(value,common_pb.AppConnectionProps.deserializeBinaryFromReader);
      msg.setCxnProps(value);
      break;
    case 5:
      var value = new common_pb.PaymentBalance;
      reader.readMessage(value,common_pb.PaymentBalance.deserializeBinaryFromReader);
      msg.setNewBalance(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setTransactionId(value);
      break;
    case 7:
      var value = new common_pb.Cash;
      reader.readMessage(value,common_pb.Cash.deserializeBinaryFromReader);
      msg.setValue(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setNarration(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.DepositCompletedEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.DepositCompletedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrgId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPurseId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCxnProps();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      common_pb.AppConnectionProps.serializeBinaryToWriter
    );
  }
  f = message.getNewBalance();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      common_pb.PaymentBalance.serializeBinaryToWriter
    );
  }
  f = message.getTransactionId();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getValue();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      common_pb.Cash.serializeBinaryToWriter
    );
  }
  f = message.getNarration();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
};


/**
 * optional string org_id = 1;
 * @return {string}
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.getOrgId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.DepositCompletedEvent} returns this
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.setOrgId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string purse_id = 2;
 * @return {string}
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.getPurseId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.DepositCompletedEvent} returns this
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.setPurseId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.Timestamp timestamp = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.com.elarian.hera.proto.DepositCompletedEvent} returns this
*/
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.DepositCompletedEvent} returns this
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional AppConnectionProps cxn_props = 4;
 * @return {?proto.com.elarian.hera.proto.AppConnectionProps}
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.getCxnProps = function() {
  return /** @type{?proto.com.elarian.hera.proto.AppConnectionProps} */ (
    jspb.Message.getWrapperField(this, common_pb.AppConnectionProps, 4));
};


/**
 * @param {?proto.com.elarian.hera.proto.AppConnectionProps|undefined} value
 * @return {!proto.com.elarian.hera.proto.DepositCompletedEvent} returns this
*/
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.setCxnProps = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.DepositCompletedEvent} returns this
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.clearCxnProps = function() {
  return this.setCxnProps(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.hasCxnProps = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional PaymentBalance new_balance = 5;
 * @return {?proto.com.elarian.hera.proto.PaymentBalance}
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.getNewBalance = function() {
  return /** @type{?proto.com.elarian.hera.proto.PaymentBalance} */ (
    jspb.Message.getWrapperField(this, common_pb.PaymentBalance, 5));
};


/**
 * @param {?proto.com.elarian.hera.proto.PaymentBalance|undefined} value
 * @return {!proto.com.elarian.hera.proto.DepositCompletedEvent} returns this
*/
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.setNewBalance = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.DepositCompletedEvent} returns this
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.clearNewBalance = function() {
  return this.setNewBalance(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.hasNewBalance = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string transaction_id = 6;
 * @return {string}
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.getTransactionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.DepositCompletedEvent} returns this
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.setTransactionId = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional Cash value = 7;
 * @return {?proto.com.elarian.hera.proto.Cash}
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.getValue = function() {
  return /** @type{?proto.com.elarian.hera.proto.Cash} */ (
    jspb.Message.getWrapperField(this, common_pb.Cash, 7));
};


/**
 * @param {?proto.com.elarian.hera.proto.Cash|undefined} value
 * @return {!proto.com.elarian.hera.proto.DepositCompletedEvent} returns this
*/
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.setValue = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.DepositCompletedEvent} returns this
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.clearValue = function() {
  return this.setValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.hasValue = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional string narration = 8;
 * @return {string}
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.getNarration = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.DepositCompletedEvent} returns this
 */
proto.com.elarian.hera.proto.DepositCompletedEvent.prototype.setNarration = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.WithdrawalInitiatedEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    orgId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    purseId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    cxnProps: (f = msg.getCxnProps()) && common_pb.AppConnectionProps.toObject(includeInstance, f),
    newBalance: (f = msg.getNewBalance()) && common_pb.PaymentBalance.toObject(includeInstance, f),
    transactionId: jspb.Message.getFieldWithDefault(msg, 6, ""),
    value: (f = msg.getValue()) && common_pb.Cash.toObject(includeInstance, f),
    narration: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.WithdrawalInitiatedEvent}
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.WithdrawalInitiatedEvent;
  return proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.WithdrawalInitiatedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.WithdrawalInitiatedEvent}
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrgId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPurseId(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 4:
      var value = new common_pb.AppConnectionProps;
      reader.readMessage(value,common_pb.AppConnectionProps.deserializeBinaryFromReader);
      msg.setCxnProps(value);
      break;
    case 5:
      var value = new common_pb.PaymentBalance;
      reader.readMessage(value,common_pb.PaymentBalance.deserializeBinaryFromReader);
      msg.setNewBalance(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setTransactionId(value);
      break;
    case 7:
      var value = new common_pb.Cash;
      reader.readMessage(value,common_pb.Cash.deserializeBinaryFromReader);
      msg.setValue(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setNarration(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.WithdrawalInitiatedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrgId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPurseId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCxnProps();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      common_pb.AppConnectionProps.serializeBinaryToWriter
    );
  }
  f = message.getNewBalance();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      common_pb.PaymentBalance.serializeBinaryToWriter
    );
  }
  f = message.getTransactionId();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getValue();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      common_pb.Cash.serializeBinaryToWriter
    );
  }
  f = message.getNarration();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
};


/**
 * optional string org_id = 1;
 * @return {string}
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.getOrgId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.WithdrawalInitiatedEvent} returns this
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.setOrgId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string purse_id = 2;
 * @return {string}
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.getPurseId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.WithdrawalInitiatedEvent} returns this
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.setPurseId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.Timestamp timestamp = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.com.elarian.hera.proto.WithdrawalInitiatedEvent} returns this
*/
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.WithdrawalInitiatedEvent} returns this
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional AppConnectionProps cxn_props = 4;
 * @return {?proto.com.elarian.hera.proto.AppConnectionProps}
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.getCxnProps = function() {
  return /** @type{?proto.com.elarian.hera.proto.AppConnectionProps} */ (
    jspb.Message.getWrapperField(this, common_pb.AppConnectionProps, 4));
};


/**
 * @param {?proto.com.elarian.hera.proto.AppConnectionProps|undefined} value
 * @return {!proto.com.elarian.hera.proto.WithdrawalInitiatedEvent} returns this
*/
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.setCxnProps = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.WithdrawalInitiatedEvent} returns this
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.clearCxnProps = function() {
  return this.setCxnProps(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.hasCxnProps = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional PaymentBalance new_balance = 5;
 * @return {?proto.com.elarian.hera.proto.PaymentBalance}
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.getNewBalance = function() {
  return /** @type{?proto.com.elarian.hera.proto.PaymentBalance} */ (
    jspb.Message.getWrapperField(this, common_pb.PaymentBalance, 5));
};


/**
 * @param {?proto.com.elarian.hera.proto.PaymentBalance|undefined} value
 * @return {!proto.com.elarian.hera.proto.WithdrawalInitiatedEvent} returns this
*/
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.setNewBalance = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.WithdrawalInitiatedEvent} returns this
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.clearNewBalance = function() {
  return this.setNewBalance(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.hasNewBalance = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string transaction_id = 6;
 * @return {string}
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.getTransactionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.WithdrawalInitiatedEvent} returns this
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.setTransactionId = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional Cash value = 7;
 * @return {?proto.com.elarian.hera.proto.Cash}
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.getValue = function() {
  return /** @type{?proto.com.elarian.hera.proto.Cash} */ (
    jspb.Message.getWrapperField(this, common_pb.Cash, 7));
};


/**
 * @param {?proto.com.elarian.hera.proto.Cash|undefined} value
 * @return {!proto.com.elarian.hera.proto.WithdrawalInitiatedEvent} returns this
*/
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.setValue = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.WithdrawalInitiatedEvent} returns this
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.clearValue = function() {
  return this.setValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.hasValue = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional string narration = 8;
 * @return {string}
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.getNarration = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.WithdrawalInitiatedEvent} returns this
 */
proto.com.elarian.hera.proto.WithdrawalInitiatedEvent.prototype.setNarration = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.WithdrawalCompletedEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.WithdrawalCompletedEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    orgId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    purseId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    newBalance: (f = msg.getNewBalance()) && common_pb.PaymentBalance.toObject(includeInstance, f),
    transactionId: jspb.Message.getFieldWithDefault(msg, 5, ""),
    value: (f = msg.getValue()) && common_pb.Cash.toObject(includeInstance, f),
    narration: jspb.Message.getFieldWithDefault(msg, 7, ""),
    status: jspb.Message.getFieldWithDefault(msg, 8, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.WithdrawalCompletedEvent}
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.WithdrawalCompletedEvent;
  return proto.com.elarian.hera.proto.WithdrawalCompletedEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.WithdrawalCompletedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.WithdrawalCompletedEvent}
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrgId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPurseId(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 4:
      var value = new common_pb.PaymentBalance;
      reader.readMessage(value,common_pb.PaymentBalance.deserializeBinaryFromReader);
      msg.setNewBalance(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setTransactionId(value);
      break;
    case 6:
      var value = new common_pb.Cash;
      reader.readMessage(value,common_pb.Cash.deserializeBinaryFromReader);
      msg.setValue(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setNarration(value);
      break;
    case 8:
      var value = /** @type {!proto.com.elarian.hera.proto.PaymentStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.WithdrawalCompletedEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.WithdrawalCompletedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrgId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPurseId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getNewBalance();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      common_pb.PaymentBalance.serializeBinaryToWriter
    );
  }
  f = message.getTransactionId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getValue();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      common_pb.Cash.serializeBinaryToWriter
    );
  }
  f = message.getNarration();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      8,
      f
    );
  }
};


/**
 * optional string org_id = 1;
 * @return {string}
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.prototype.getOrgId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.WithdrawalCompletedEvent} returns this
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.prototype.setOrgId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string purse_id = 2;
 * @return {string}
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.prototype.getPurseId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.WithdrawalCompletedEvent} returns this
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.prototype.setPurseId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.Timestamp timestamp = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.com.elarian.hera.proto.WithdrawalCompletedEvent} returns this
*/
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.WithdrawalCompletedEvent} returns this
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional PaymentBalance new_balance = 4;
 * @return {?proto.com.elarian.hera.proto.PaymentBalance}
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.prototype.getNewBalance = function() {
  return /** @type{?proto.com.elarian.hera.proto.PaymentBalance} */ (
    jspb.Message.getWrapperField(this, common_pb.PaymentBalance, 4));
};


/**
 * @param {?proto.com.elarian.hera.proto.PaymentBalance|undefined} value
 * @return {!proto.com.elarian.hera.proto.WithdrawalCompletedEvent} returns this
*/
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.prototype.setNewBalance = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.WithdrawalCompletedEvent} returns this
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.prototype.clearNewBalance = function() {
  return this.setNewBalance(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.prototype.hasNewBalance = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string transaction_id = 5;
 * @return {string}
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.prototype.getTransactionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.WithdrawalCompletedEvent} returns this
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.prototype.setTransactionId = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional Cash value = 6;
 * @return {?proto.com.elarian.hera.proto.Cash}
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.prototype.getValue = function() {
  return /** @type{?proto.com.elarian.hera.proto.Cash} */ (
    jspb.Message.getWrapperField(this, common_pb.Cash, 6));
};


/**
 * @param {?proto.com.elarian.hera.proto.Cash|undefined} value
 * @return {!proto.com.elarian.hera.proto.WithdrawalCompletedEvent} returns this
*/
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.prototype.setValue = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.WithdrawalCompletedEvent} returns this
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.prototype.clearValue = function() {
  return this.setValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.prototype.hasValue = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string narration = 7;
 * @return {string}
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.prototype.getNarration = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.WithdrawalCompletedEvent} returns this
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.prototype.setNarration = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional PaymentStatus status = 8;
 * @return {!proto.com.elarian.hera.proto.PaymentStatus}
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.prototype.getStatus = function() {
  return /** @type {!proto.com.elarian.hera.proto.PaymentStatus} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {!proto.com.elarian.hera.proto.PaymentStatus} value
 * @return {!proto.com.elarian.hera.proto.WithdrawalCompletedEvent} returns this
 */
proto.com.elarian.hera.proto.WithdrawalCompletedEvent.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 8, value);
};


goog.object.extend(exports, proto.com.elarian.hera.proto);
