/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.com.elarian.hera.proto.ReplyToMessageRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.com.elarian.hera.proto.CustomerMessageBody');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.ReplyToMessageRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.elarian.hera.proto.ReplyToMessageRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.elarian.hera.proto.ReplyToMessageRequest.displayName = 'proto.com.elarian.hera.proto.ReplyToMessageRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.ReplyToMessageRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.ReplyToMessageRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.ReplyToMessageRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.ReplyToMessageRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    appId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    productId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    customerId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    replyToMessageId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    body: (f = msg.getBody()) && proto.com.elarian.hera.proto.CustomerMessageBody.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.ReplyToMessageRequest}
 */
proto.com.elarian.hera.proto.ReplyToMessageRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.ReplyToMessageRequest;
  return proto.com.elarian.hera.proto.ReplyToMessageRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.ReplyToMessageRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.ReplyToMessageRequest}
 */
proto.com.elarian.hera.proto.ReplyToMessageRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAppId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setProductId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCustomerId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setReplyToMessageId(value);
      break;
    case 5:
      var value = new proto.com.elarian.hera.proto.CustomerMessageBody;
      reader.readMessage(value,proto.com.elarian.hera.proto.CustomerMessageBody.deserializeBinaryFromReader);
      msg.setBody(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.ReplyToMessageRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.ReplyToMessageRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.ReplyToMessageRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.ReplyToMessageRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAppId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getProductId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCustomerId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getReplyToMessageId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getBody();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.com.elarian.hera.proto.CustomerMessageBody.serializeBinaryToWriter
    );
  }
};


/**
 * optional string app_id = 1;
 * @return {string}
 */
proto.com.elarian.hera.proto.ReplyToMessageRequest.prototype.getAppId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.elarian.hera.proto.ReplyToMessageRequest.prototype.setAppId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string product_id = 2;
 * @return {string}
 */
proto.com.elarian.hera.proto.ReplyToMessageRequest.prototype.getProductId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.com.elarian.hera.proto.ReplyToMessageRequest.prototype.setProductId = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string customer_id = 3;
 * @return {string}
 */
proto.com.elarian.hera.proto.ReplyToMessageRequest.prototype.getCustomerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.com.elarian.hera.proto.ReplyToMessageRequest.prototype.setCustomerId = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string reply_to_message_id = 4;
 * @return {string}
 */
proto.com.elarian.hera.proto.ReplyToMessageRequest.prototype.getReplyToMessageId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.com.elarian.hera.proto.ReplyToMessageRequest.prototype.setReplyToMessageId = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional CustomerMessageBody body = 5;
 * @return {?proto.com.elarian.hera.proto.CustomerMessageBody}
 */
proto.com.elarian.hera.proto.ReplyToMessageRequest.prototype.getBody = function() {
  return /** @type{?proto.com.elarian.hera.proto.CustomerMessageBody} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.CustomerMessageBody, 5));
};


/** @param {?proto.com.elarian.hera.proto.CustomerMessageBody|undefined} value */
proto.com.elarian.hera.proto.ReplyToMessageRequest.prototype.setBody = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.com.elarian.hera.proto.ReplyToMessageRequest.prototype.clearBody = function() {
  this.setBody(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.ReplyToMessageRequest.prototype.hasBody = function() {
  return jspb.Message.getField(this, 5) != null;
};


