/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.com.elarian.hera.proto.CustomerIndex');
goog.require('proto.com.elarian.hera.proto.CustomerNumber');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.repeatedFields_, proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.oneofGroups_);
};
goog.inherits(proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.displayName = 'proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.repeatedFields_ = [4];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.oneofGroups_ = [[2,3]];

/**
 * @enum {number}
 */
proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.CustomerCase = {
  CUSTOMER_NOT_SET: 0,
  CUSTOMER_ID: 2,
  CUSTOMER_NUMBER: 3
};

/**
 * @return {proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.CustomerCase}
 */
proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.prototype.getCustomerCase = function() {
  return /** @type {proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.CustomerCase} */(jspb.Message.computeOneofCase(this, proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    appid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    customerId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    customerNumber: (f = msg.getCustomerNumber()) && proto.com.elarian.hera.proto.CustomerNumber.toObject(includeInstance, f),
    secondaryIdsList: jspb.Message.toObjectList(msg.getSecondaryIdsList(),
    proto.com.elarian.hera.proto.CustomerIndex.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest}
 */
proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest;
  return proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest}
 */
proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAppid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCustomerId(value);
      break;
    case 3:
      var value = new proto.com.elarian.hera.proto.CustomerNumber;
      reader.readMessage(value,proto.com.elarian.hera.proto.CustomerNumber.deserializeBinaryFromReader);
      msg.setCustomerNumber(value);
      break;
    case 4:
      var value = new proto.com.elarian.hera.proto.CustomerIndex;
      reader.readMessage(value,proto.com.elarian.hera.proto.CustomerIndex.deserializeBinaryFromReader);
      msg.addSecondaryIds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAppid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCustomerNumber();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.com.elarian.hera.proto.CustomerNumber.serializeBinaryToWriter
    );
  }
  f = message.getSecondaryIdsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.com.elarian.hera.proto.CustomerIndex.serializeBinaryToWriter
    );
  }
};


/**
 * optional string appId = 1;
 * @return {string}
 */
proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.prototype.getAppid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.prototype.setAppid = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string customer_id = 2;
 * @return {string}
 */
proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.prototype.getCustomerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.prototype.setCustomerId = function(value) {
  jspb.Message.setOneofField(this, 2, proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.oneofGroups_[0], value);
};


proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.prototype.clearCustomerId = function() {
  jspb.Message.setOneofField(this, 2, proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.prototype.hasCustomerId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional CustomerNumber customer_number = 3;
 * @return {?proto.com.elarian.hera.proto.CustomerNumber}
 */
proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.prototype.getCustomerNumber = function() {
  return /** @type{?proto.com.elarian.hera.proto.CustomerNumber} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.CustomerNumber, 3));
};


/** @param {?proto.com.elarian.hera.proto.CustomerNumber|undefined} value */
proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.prototype.setCustomerNumber = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.oneofGroups_[0], value);
};


proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.prototype.clearCustomerNumber = function() {
  this.setCustomerNumber(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.prototype.hasCustomerNumber = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated CustomerIndex secondary_ids = 4;
 * @return {!Array.<!proto.com.elarian.hera.proto.CustomerIndex>}
 */
proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.prototype.getSecondaryIdsList = function() {
  return /** @type{!Array.<!proto.com.elarian.hera.proto.CustomerIndex>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.elarian.hera.proto.CustomerIndex, 4));
};


/** @param {!Array.<!proto.com.elarian.hera.proto.CustomerIndex>} value */
proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.prototype.setSecondaryIdsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.com.elarian.hera.proto.CustomerIndex=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.elarian.hera.proto.CustomerIndex}
 */
proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.prototype.addSecondaryIds = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.com.elarian.hera.proto.CustomerIndex, opt_index);
};


proto.com.elarian.hera.proto.UpdateCustomerSecondaryIdRequest.prototype.clearSecondaryIdsList = function() {
  this.setSecondaryIdsList([]);
};


