/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.com.elarian.hera.proto.VoiceCallStatus');

/**
 * @enum {number}
 */
proto.com.elarian.hera.proto.VoiceCallStatus = {
  VOICE_CALL_STATUS_UNSPECIFIED: 0,
  VOICE_CALL_STATUS_QUEUED: 100,
  VOICE_CALL_STATUS_ANSWERED: 101,
  VOICE_CALL_STATUS_RINGING: 102,
  VOICE_CALL_STATUS_ACTIVE: 200,
  VOICE_CALL_STATUS_DIALING: 201,
  VOICE_CALL_STATUS_DIAL_COMPLETED: 202,
  VOICE_CALL_STATUS_BRIDGED: 203,
  VOICE_CALL_STATUS_ENQUEUED: 204,
  VOICE_CALL_STATUS_DEQUEUED: 205,
  VOICE_CALL_STATUS_TRANSFERRED: 206,
  VOICE_CALL_STATUS_TRANSFER_COMPLETED: 207,
  VOICE_CALL_STATUS_COMPLETED: 300,
  VOICE_CALL_STATUS_INSUFFICIENT_CREDIT: 400,
  VOICE_CALL_STATUS_NOT_ANSWERED: 401,
  VOICE_CALL_STATUS_INVALID_PHONE_NUMBER: 402,
  VOICE_CALL_STATUS_DESTINATION_NOT_SUPPORTED: 403,
  VOICE_CALL_STATUS_DECOMMISSIONED_CUSTOMERID: 404,
  VOICE_CALL_STATUS_EXPIRED: 405,
  VOICE_CALL_STATUS_APPLICATION_ERROR: 501
};

