/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.com.elarian.hera.proto.VoiceCallAction');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.com.elarian.hera.proto.DequeueCallAction');
goog.require('proto.com.elarian.hera.proto.DialCallAction');
goog.require('proto.com.elarian.hera.proto.EnqueueCallAction');
goog.require('proto.com.elarian.hera.proto.GetDigitsCallAction');
goog.require('proto.com.elarian.hera.proto.GetRecordingCallAction');
goog.require('proto.com.elarian.hera.proto.PlayCallAction');
goog.require('proto.com.elarian.hera.proto.RecordSessionCallAction');
goog.require('proto.com.elarian.hera.proto.RedirectCallAction');
goog.require('proto.com.elarian.hera.proto.RejectCallAction');
goog.require('proto.com.elarian.hera.proto.SayCallAction');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.VoiceCallAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.com.elarian.hera.proto.VoiceCallAction.oneofGroups_);
};
goog.inherits(proto.com.elarian.hera.proto.VoiceCallAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.elarian.hera.proto.VoiceCallAction.displayName = 'proto.com.elarian.hera.proto.VoiceCallAction';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.com.elarian.hera.proto.VoiceCallAction.oneofGroups_ = [[1,2,3,4,5,6,7,8,9,10]];

/**
 * @enum {number}
 */
proto.com.elarian.hera.proto.VoiceCallAction.EntryCase = {
  ENTRY_NOT_SET: 0,
  SAY: 1,
  PLAY: 2,
  GET_DIGITS: 3,
  DIAL: 4,
  RECORD_SESSION: 5,
  GET_RECORDING: 6,
  ENQUEUE: 7,
  DEQUEUE: 8,
  REJECT: 9,
  REDIRECT: 10
};

/**
 * @return {proto.com.elarian.hera.proto.VoiceCallAction.EntryCase}
 */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.getEntryCase = function() {
  return /** @type {proto.com.elarian.hera.proto.VoiceCallAction.EntryCase} */(jspb.Message.computeOneofCase(this, proto.com.elarian.hera.proto.VoiceCallAction.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.VoiceCallAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.VoiceCallAction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.VoiceCallAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    say: (f = msg.getSay()) && proto.com.elarian.hera.proto.SayCallAction.toObject(includeInstance, f),
    play: (f = msg.getPlay()) && proto.com.elarian.hera.proto.PlayCallAction.toObject(includeInstance, f),
    getDigits: (f = msg.getGetDigits()) && proto.com.elarian.hera.proto.GetDigitsCallAction.toObject(includeInstance, f),
    dial: (f = msg.getDial()) && proto.com.elarian.hera.proto.DialCallAction.toObject(includeInstance, f),
    recordSession: (f = msg.getRecordSession()) && proto.com.elarian.hera.proto.RecordSessionCallAction.toObject(includeInstance, f),
    getRecording: (f = msg.getGetRecording()) && proto.com.elarian.hera.proto.GetRecordingCallAction.toObject(includeInstance, f),
    enqueue: (f = msg.getEnqueue()) && proto.com.elarian.hera.proto.EnqueueCallAction.toObject(includeInstance, f),
    dequeue: (f = msg.getDequeue()) && proto.com.elarian.hera.proto.DequeueCallAction.toObject(includeInstance, f),
    reject: (f = msg.getReject()) && proto.com.elarian.hera.proto.RejectCallAction.toObject(includeInstance, f),
    redirect: (f = msg.getRedirect()) && proto.com.elarian.hera.proto.RedirectCallAction.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.VoiceCallAction}
 */
proto.com.elarian.hera.proto.VoiceCallAction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.VoiceCallAction;
  return proto.com.elarian.hera.proto.VoiceCallAction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.VoiceCallAction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.VoiceCallAction}
 */
proto.com.elarian.hera.proto.VoiceCallAction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.elarian.hera.proto.SayCallAction;
      reader.readMessage(value,proto.com.elarian.hera.proto.SayCallAction.deserializeBinaryFromReader);
      msg.setSay(value);
      break;
    case 2:
      var value = new proto.com.elarian.hera.proto.PlayCallAction;
      reader.readMessage(value,proto.com.elarian.hera.proto.PlayCallAction.deserializeBinaryFromReader);
      msg.setPlay(value);
      break;
    case 3:
      var value = new proto.com.elarian.hera.proto.GetDigitsCallAction;
      reader.readMessage(value,proto.com.elarian.hera.proto.GetDigitsCallAction.deserializeBinaryFromReader);
      msg.setGetDigits(value);
      break;
    case 4:
      var value = new proto.com.elarian.hera.proto.DialCallAction;
      reader.readMessage(value,proto.com.elarian.hera.proto.DialCallAction.deserializeBinaryFromReader);
      msg.setDial(value);
      break;
    case 5:
      var value = new proto.com.elarian.hera.proto.RecordSessionCallAction;
      reader.readMessage(value,proto.com.elarian.hera.proto.RecordSessionCallAction.deserializeBinaryFromReader);
      msg.setRecordSession(value);
      break;
    case 6:
      var value = new proto.com.elarian.hera.proto.GetRecordingCallAction;
      reader.readMessage(value,proto.com.elarian.hera.proto.GetRecordingCallAction.deserializeBinaryFromReader);
      msg.setGetRecording(value);
      break;
    case 7:
      var value = new proto.com.elarian.hera.proto.EnqueueCallAction;
      reader.readMessage(value,proto.com.elarian.hera.proto.EnqueueCallAction.deserializeBinaryFromReader);
      msg.setEnqueue(value);
      break;
    case 8:
      var value = new proto.com.elarian.hera.proto.DequeueCallAction;
      reader.readMessage(value,proto.com.elarian.hera.proto.DequeueCallAction.deserializeBinaryFromReader);
      msg.setDequeue(value);
      break;
    case 9:
      var value = new proto.com.elarian.hera.proto.RejectCallAction;
      reader.readMessage(value,proto.com.elarian.hera.proto.RejectCallAction.deserializeBinaryFromReader);
      msg.setReject(value);
      break;
    case 10:
      var value = new proto.com.elarian.hera.proto.RedirectCallAction;
      reader.readMessage(value,proto.com.elarian.hera.proto.RedirectCallAction.deserializeBinaryFromReader);
      msg.setRedirect(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.VoiceCallAction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.VoiceCallAction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.VoiceCallAction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSay();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.com.elarian.hera.proto.SayCallAction.serializeBinaryToWriter
    );
  }
  f = message.getPlay();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.com.elarian.hera.proto.PlayCallAction.serializeBinaryToWriter
    );
  }
  f = message.getGetDigits();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.com.elarian.hera.proto.GetDigitsCallAction.serializeBinaryToWriter
    );
  }
  f = message.getDial();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.com.elarian.hera.proto.DialCallAction.serializeBinaryToWriter
    );
  }
  f = message.getRecordSession();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.com.elarian.hera.proto.RecordSessionCallAction.serializeBinaryToWriter
    );
  }
  f = message.getGetRecording();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.com.elarian.hera.proto.GetRecordingCallAction.serializeBinaryToWriter
    );
  }
  f = message.getEnqueue();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.com.elarian.hera.proto.EnqueueCallAction.serializeBinaryToWriter
    );
  }
  f = message.getDequeue();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.com.elarian.hera.proto.DequeueCallAction.serializeBinaryToWriter
    );
  }
  f = message.getReject();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.com.elarian.hera.proto.RejectCallAction.serializeBinaryToWriter
    );
  }
  f = message.getRedirect();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.com.elarian.hera.proto.RedirectCallAction.serializeBinaryToWriter
    );
  }
};


/**
 * optional SayCallAction say = 1;
 * @return {?proto.com.elarian.hera.proto.SayCallAction}
 */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.getSay = function() {
  return /** @type{?proto.com.elarian.hera.proto.SayCallAction} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.SayCallAction, 1));
};


/** @param {?proto.com.elarian.hera.proto.SayCallAction|undefined} value */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.setSay = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.com.elarian.hera.proto.VoiceCallAction.oneofGroups_[0], value);
};


proto.com.elarian.hera.proto.VoiceCallAction.prototype.clearSay = function() {
  this.setSay(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.hasSay = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional PlayCallAction play = 2;
 * @return {?proto.com.elarian.hera.proto.PlayCallAction}
 */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.getPlay = function() {
  return /** @type{?proto.com.elarian.hera.proto.PlayCallAction} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.PlayCallAction, 2));
};


/** @param {?proto.com.elarian.hera.proto.PlayCallAction|undefined} value */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.setPlay = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.com.elarian.hera.proto.VoiceCallAction.oneofGroups_[0], value);
};


proto.com.elarian.hera.proto.VoiceCallAction.prototype.clearPlay = function() {
  this.setPlay(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.hasPlay = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional GetDigitsCallAction get_digits = 3;
 * @return {?proto.com.elarian.hera.proto.GetDigitsCallAction}
 */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.getGetDigits = function() {
  return /** @type{?proto.com.elarian.hera.proto.GetDigitsCallAction} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.GetDigitsCallAction, 3));
};


/** @param {?proto.com.elarian.hera.proto.GetDigitsCallAction|undefined} value */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.setGetDigits = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.com.elarian.hera.proto.VoiceCallAction.oneofGroups_[0], value);
};


proto.com.elarian.hera.proto.VoiceCallAction.prototype.clearGetDigits = function() {
  this.setGetDigits(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.hasGetDigits = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional DialCallAction dial = 4;
 * @return {?proto.com.elarian.hera.proto.DialCallAction}
 */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.getDial = function() {
  return /** @type{?proto.com.elarian.hera.proto.DialCallAction} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.DialCallAction, 4));
};


/** @param {?proto.com.elarian.hera.proto.DialCallAction|undefined} value */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.setDial = function(value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.com.elarian.hera.proto.VoiceCallAction.oneofGroups_[0], value);
};


proto.com.elarian.hera.proto.VoiceCallAction.prototype.clearDial = function() {
  this.setDial(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.hasDial = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional RecordSessionCallAction record_session = 5;
 * @return {?proto.com.elarian.hera.proto.RecordSessionCallAction}
 */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.getRecordSession = function() {
  return /** @type{?proto.com.elarian.hera.proto.RecordSessionCallAction} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.RecordSessionCallAction, 5));
};


/** @param {?proto.com.elarian.hera.proto.RecordSessionCallAction|undefined} value */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.setRecordSession = function(value) {
  jspb.Message.setOneofWrapperField(this, 5, proto.com.elarian.hera.proto.VoiceCallAction.oneofGroups_[0], value);
};


proto.com.elarian.hera.proto.VoiceCallAction.prototype.clearRecordSession = function() {
  this.setRecordSession(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.hasRecordSession = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional GetRecordingCallAction get_recording = 6;
 * @return {?proto.com.elarian.hera.proto.GetRecordingCallAction}
 */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.getGetRecording = function() {
  return /** @type{?proto.com.elarian.hera.proto.GetRecordingCallAction} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.GetRecordingCallAction, 6));
};


/** @param {?proto.com.elarian.hera.proto.GetRecordingCallAction|undefined} value */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.setGetRecording = function(value) {
  jspb.Message.setOneofWrapperField(this, 6, proto.com.elarian.hera.proto.VoiceCallAction.oneofGroups_[0], value);
};


proto.com.elarian.hera.proto.VoiceCallAction.prototype.clearGetRecording = function() {
  this.setGetRecording(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.hasGetRecording = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional EnqueueCallAction enqueue = 7;
 * @return {?proto.com.elarian.hera.proto.EnqueueCallAction}
 */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.getEnqueue = function() {
  return /** @type{?proto.com.elarian.hera.proto.EnqueueCallAction} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.EnqueueCallAction, 7));
};


/** @param {?proto.com.elarian.hera.proto.EnqueueCallAction|undefined} value */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.setEnqueue = function(value) {
  jspb.Message.setOneofWrapperField(this, 7, proto.com.elarian.hera.proto.VoiceCallAction.oneofGroups_[0], value);
};


proto.com.elarian.hera.proto.VoiceCallAction.prototype.clearEnqueue = function() {
  this.setEnqueue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.hasEnqueue = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional DequeueCallAction dequeue = 8;
 * @return {?proto.com.elarian.hera.proto.DequeueCallAction}
 */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.getDequeue = function() {
  return /** @type{?proto.com.elarian.hera.proto.DequeueCallAction} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.DequeueCallAction, 8));
};


/** @param {?proto.com.elarian.hera.proto.DequeueCallAction|undefined} value */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.setDequeue = function(value) {
  jspb.Message.setOneofWrapperField(this, 8, proto.com.elarian.hera.proto.VoiceCallAction.oneofGroups_[0], value);
};


proto.com.elarian.hera.proto.VoiceCallAction.prototype.clearDequeue = function() {
  this.setDequeue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.hasDequeue = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional RejectCallAction reject = 9;
 * @return {?proto.com.elarian.hera.proto.RejectCallAction}
 */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.getReject = function() {
  return /** @type{?proto.com.elarian.hera.proto.RejectCallAction} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.RejectCallAction, 9));
};


/** @param {?proto.com.elarian.hera.proto.RejectCallAction|undefined} value */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.setReject = function(value) {
  jspb.Message.setOneofWrapperField(this, 9, proto.com.elarian.hera.proto.VoiceCallAction.oneofGroups_[0], value);
};


proto.com.elarian.hera.proto.VoiceCallAction.prototype.clearReject = function() {
  this.setReject(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.hasReject = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional RedirectCallAction redirect = 10;
 * @return {?proto.com.elarian.hera.proto.RedirectCallAction}
 */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.getRedirect = function() {
  return /** @type{?proto.com.elarian.hera.proto.RedirectCallAction} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.RedirectCallAction, 10));
};


/** @param {?proto.com.elarian.hera.proto.RedirectCallAction|undefined} value */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.setRedirect = function(value) {
  jspb.Message.setOneofWrapperField(this, 10, proto.com.elarian.hera.proto.VoiceCallAction.oneofGroups_[0], value);
};


proto.com.elarian.hera.proto.VoiceCallAction.prototype.clearRedirect = function() {
  this.setRedirect(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.elarian.hera.proto.VoiceCallAction.prototype.hasRedirect = function() {
  return jspb.Message.getField(this, 10) != null;
};


