/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.com.elarian.hera.proto.VoiceCallHangupCause');

/**
 * @enum {number}
 */
proto.com.elarian.hera.proto.VoiceCallHangupCause = {
  VOICE_CALL_HANGUP_CAUSE_UNSPECIFIED: 0,
  VOICE_CALL_HANGUP_CAUSE_UNALLOCATED_NUMBER: 1,
  VOICE_CALL_HANGUP_CAUSE_USER_BUSY: 17,
  VOICE_CALL_HANGUP_CAUSE_NORMAL_CLEARING: 16,
  VOICE_CALL_HANGUP_CAUSE_NO_USER_RESPONSE: 18,
  VOICE_CALL_HANGUP_CAUSE_NO_ANSWER: 19,
  VOICE_CALL_HANGUP_CAUSE_SUBSCRIBER_ABSENT: 20,
  VOICE_CALL_HANGUP_CAUSE_CALL_REJECTED: 21,
  VOICE_CALL_HANGUP_CAUSE_NORMAL_UNSPECIFIED: 31,
  VOICE_CALL_HANGUP_CAUSE_NORMAL_TEMPORARY_FAILURE: 41,
  VOICE_CALL_HANGUP_CAUSE_SERVICE_UNAVAILABLE: 63,
  VOICE_CALL_HANGUP_CAUSE_RECOVERY_ON_TIMER_EXPIRE: 102,
  VOICE_CALL_HANGUP_CAUSE_ORIGINATOR_CANCEL: 487,
  VOICE_CALL_HANGUP_CAUSE_LOSE_RACE: 502,
  VOICE_CALL_HANGUP_CAUSE_USER_NOT_REGISTERED: 606
};

