/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.com.elarian.hera.proto.VoiceState');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.com.elarian.hera.proto.CustomerNumber');
goog.require('proto.com.elarian.hera.proto.VoiceCallStateEntry');
goog.require('proto.com.elarian.hera.proto.VoiceChannelNumber');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.VoiceState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.elarian.hera.proto.VoiceState.repeatedFields_, null);
};
goog.inherits(proto.com.elarian.hera.proto.VoiceState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.elarian.hera.proto.VoiceState.displayName = 'proto.com.elarian.hera.proto.VoiceState';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.elarian.hera.proto.VoiceState.repeatedFields_ = [1,2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.VoiceState.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.VoiceState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.VoiceState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.VoiceState.toObject = function(includeInstance, msg) {
  var f, obj = {
    callsList: jspb.Message.toObjectList(msg.getCallsList(),
    proto.com.elarian.hera.proto.VoiceCallStateEntry.toObject, includeInstance),
    customerNumbersList: jspb.Message.toObjectList(msg.getCustomerNumbersList(),
    proto.com.elarian.hera.proto.CustomerNumber.toObject, includeInstance),
    channelNumbersList: jspb.Message.toObjectList(msg.getChannelNumbersList(),
    proto.com.elarian.hera.proto.VoiceChannelNumber.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.VoiceState}
 */
proto.com.elarian.hera.proto.VoiceState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.VoiceState;
  return proto.com.elarian.hera.proto.VoiceState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.VoiceState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.VoiceState}
 */
proto.com.elarian.hera.proto.VoiceState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.elarian.hera.proto.VoiceCallStateEntry;
      reader.readMessage(value,proto.com.elarian.hera.proto.VoiceCallStateEntry.deserializeBinaryFromReader);
      msg.addCalls(value);
      break;
    case 2:
      var value = new proto.com.elarian.hera.proto.CustomerNumber;
      reader.readMessage(value,proto.com.elarian.hera.proto.CustomerNumber.deserializeBinaryFromReader);
      msg.addCustomerNumbers(value);
      break;
    case 3:
      var value = new proto.com.elarian.hera.proto.VoiceChannelNumber;
      reader.readMessage(value,proto.com.elarian.hera.proto.VoiceChannelNumber.deserializeBinaryFromReader);
      msg.addChannelNumbers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.VoiceState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.VoiceState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.VoiceState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.VoiceState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCallsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.com.elarian.hera.proto.VoiceCallStateEntry.serializeBinaryToWriter
    );
  }
  f = message.getCustomerNumbersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.com.elarian.hera.proto.CustomerNumber.serializeBinaryToWriter
    );
  }
  f = message.getChannelNumbersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.com.elarian.hera.proto.VoiceChannelNumber.serializeBinaryToWriter
    );
  }
};


/**
 * repeated VoiceCallStateEntry calls = 1;
 * @return {!Array.<!proto.com.elarian.hera.proto.VoiceCallStateEntry>}
 */
proto.com.elarian.hera.proto.VoiceState.prototype.getCallsList = function() {
  return /** @type{!Array.<!proto.com.elarian.hera.proto.VoiceCallStateEntry>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.elarian.hera.proto.VoiceCallStateEntry, 1));
};


/** @param {!Array.<!proto.com.elarian.hera.proto.VoiceCallStateEntry>} value */
proto.com.elarian.hera.proto.VoiceState.prototype.setCallsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.com.elarian.hera.proto.VoiceCallStateEntry=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.elarian.hera.proto.VoiceCallStateEntry}
 */
proto.com.elarian.hera.proto.VoiceState.prototype.addCalls = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.com.elarian.hera.proto.VoiceCallStateEntry, opt_index);
};


proto.com.elarian.hera.proto.VoiceState.prototype.clearCallsList = function() {
  this.setCallsList([]);
};


/**
 * repeated CustomerNumber customer_numbers = 2;
 * @return {!Array.<!proto.com.elarian.hera.proto.CustomerNumber>}
 */
proto.com.elarian.hera.proto.VoiceState.prototype.getCustomerNumbersList = function() {
  return /** @type{!Array.<!proto.com.elarian.hera.proto.CustomerNumber>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.elarian.hera.proto.CustomerNumber, 2));
};


/** @param {!Array.<!proto.com.elarian.hera.proto.CustomerNumber>} value */
proto.com.elarian.hera.proto.VoiceState.prototype.setCustomerNumbersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.com.elarian.hera.proto.CustomerNumber=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.elarian.hera.proto.CustomerNumber}
 */
proto.com.elarian.hera.proto.VoiceState.prototype.addCustomerNumbers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.com.elarian.hera.proto.CustomerNumber, opt_index);
};


proto.com.elarian.hera.proto.VoiceState.prototype.clearCustomerNumbersList = function() {
  this.setCustomerNumbersList([]);
};


/**
 * repeated VoiceChannelNumber channel_numbers = 3;
 * @return {!Array.<!proto.com.elarian.hera.proto.VoiceChannelNumber>}
 */
proto.com.elarian.hera.proto.VoiceState.prototype.getChannelNumbersList = function() {
  return /** @type{!Array.<!proto.com.elarian.hera.proto.VoiceChannelNumber>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.elarian.hera.proto.VoiceChannelNumber, 3));
};


/** @param {!Array.<!proto.com.elarian.hera.proto.VoiceChannelNumber>} value */
proto.com.elarian.hera.proto.VoiceState.prototype.setChannelNumbersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.com.elarian.hera.proto.VoiceChannelNumber=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.elarian.hera.proto.VoiceChannelNumber}
 */
proto.com.elarian.hera.proto.VoiceState.prototype.addChannelNumbers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.com.elarian.hera.proto.VoiceChannelNumber, opt_index);
};


proto.com.elarian.hera.proto.VoiceState.prototype.clearChannelNumbersList = function() {
  this.setChannelNumbersList([]);
};


