// source: web.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var common_pb = require('./common_pb.js');
goog.object.extend(proto, common_pb);
goog.exportSymbol('proto.com.elarian.hera.proto.WebActionEvent', null, global);
goog.exportSymbol('proto.com.elarian.hera.proto.WebEntityDecommissionedEvent', null, global);
goog.exportSymbol('proto.com.elarian.hera.proto.WebEvent', null, global);
goog.exportSymbol('proto.com.elarian.hera.proto.WebEvent.EventCase', null, global);
goog.exportSymbol('proto.com.elarian.hera.proto.WebSessionStateEntry', null, global);
goog.exportSymbol('proto.com.elarian.hera.proto.WebState', null, global);
goog.exportSymbol('proto.com.elarian.hera.proto.WebStateAdoptedEvent', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.WebSessionStateEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.elarian.hera.proto.WebSessionStateEntry.repeatedFields_, null);
};
goog.inherits(proto.com.elarian.hera.proto.WebSessionStateEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.elarian.hera.proto.WebSessionStateEntry.displayName = 'proto.com.elarian.hera.proto.WebSessionStateEntry';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.WebState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.elarian.hera.proto.WebState.repeatedFields_, null);
};
goog.inherits(proto.com.elarian.hera.proto.WebState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.elarian.hera.proto.WebState.displayName = 'proto.com.elarian.hera.proto.WebState';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.WebEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.com.elarian.hera.proto.WebEvent.oneofGroups_);
};
goog.inherits(proto.com.elarian.hera.proto.WebEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.elarian.hera.proto.WebEvent.displayName = 'proto.com.elarian.hera.proto.WebEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.WebStateAdoptedEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.elarian.hera.proto.WebStateAdoptedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.elarian.hera.proto.WebStateAdoptedEvent.displayName = 'proto.com.elarian.hera.proto.WebStateAdoptedEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.WebEntityDecommissionedEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.elarian.hera.proto.WebEntityDecommissionedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.displayName = 'proto.com.elarian.hera.proto.WebEntityDecommissionedEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.elarian.hera.proto.WebActionEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.elarian.hera.proto.WebActionEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.elarian.hera.proto.WebActionEvent.displayName = 'proto.com.elarian.hera.proto.WebActionEvent';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.WebSessionStateEntry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.WebSessionStateEntry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.toObject = function(includeInstance, msg) {
  var f, obj = {
    customerNumber: (f = msg.getCustomerNumber()) && common_pb.CustomerNumber.toObject(includeInstance, f),
    channelNumber: (f = msg.getChannelNumber()) && common_pb.WebChannelNumber.toObject(includeInstance, f),
    sessionId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    appId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    actionsList: jspb.Message.toObjectList(msg.getActionsList(),
    common_pb.WebAction.toObject, includeInstance),
    createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.WebSessionStateEntry}
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.WebSessionStateEntry;
  return proto.com.elarian.hera.proto.WebSessionStateEntry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.WebSessionStateEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.WebSessionStateEntry}
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_pb.CustomerNumber;
      reader.readMessage(value,common_pb.CustomerNumber.deserializeBinaryFromReader);
      msg.setCustomerNumber(value);
      break;
    case 2:
      var value = new common_pb.WebChannelNumber;
      reader.readMessage(value,common_pb.WebChannelNumber.deserializeBinaryFromReader);
      msg.setChannelNumber(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSessionId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setAppId(value);
      break;
    case 5:
      var value = new common_pb.WebAction;
      reader.readMessage(value,common_pb.WebAction.deserializeBinaryFromReader);
      msg.addActions(value);
      break;
    case 6:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 7:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.WebSessionStateEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.WebSessionStateEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCustomerNumber();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_pb.CustomerNumber.serializeBinaryToWriter
    );
  }
  f = message.getChannelNumber();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      common_pb.WebChannelNumber.serializeBinaryToWriter
    );
  }
  f = message.getSessionId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAppId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getActionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      common_pb.WebAction.serializeBinaryToWriter
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional CustomerNumber customer_number = 1;
 * @return {?proto.com.elarian.hera.proto.CustomerNumber}
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.getCustomerNumber = function() {
  return /** @type{?proto.com.elarian.hera.proto.CustomerNumber} */ (
    jspb.Message.getWrapperField(this, common_pb.CustomerNumber, 1));
};


/**
 * @param {?proto.com.elarian.hera.proto.CustomerNumber|undefined} value
 * @return {!proto.com.elarian.hera.proto.WebSessionStateEntry} returns this
*/
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.setCustomerNumber = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.WebSessionStateEntry} returns this
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.clearCustomerNumber = function() {
  return this.setCustomerNumber(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.hasCustomerNumber = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional WebChannelNumber channel_number = 2;
 * @return {?proto.com.elarian.hera.proto.WebChannelNumber}
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.getChannelNumber = function() {
  return /** @type{?proto.com.elarian.hera.proto.WebChannelNumber} */ (
    jspb.Message.getWrapperField(this, common_pb.WebChannelNumber, 2));
};


/**
 * @param {?proto.com.elarian.hera.proto.WebChannelNumber|undefined} value
 * @return {!proto.com.elarian.hera.proto.WebSessionStateEntry} returns this
*/
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.setChannelNumber = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.WebSessionStateEntry} returns this
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.clearChannelNumber = function() {
  return this.setChannelNumber(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.hasChannelNumber = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string session_id = 3;
 * @return {string}
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.getSessionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.WebSessionStateEntry} returns this
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.setSessionId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string app_id = 4;
 * @return {string}
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.getAppId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.WebSessionStateEntry} returns this
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.setAppId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * repeated WebAction actions = 5;
 * @return {!Array<!proto.com.elarian.hera.proto.WebAction>}
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.getActionsList = function() {
  return /** @type{!Array<!proto.com.elarian.hera.proto.WebAction>} */ (
    jspb.Message.getRepeatedWrapperField(this, common_pb.WebAction, 5));
};


/**
 * @param {!Array<!proto.com.elarian.hera.proto.WebAction>} value
 * @return {!proto.com.elarian.hera.proto.WebSessionStateEntry} returns this
*/
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.setActionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.com.elarian.hera.proto.WebAction=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.elarian.hera.proto.WebAction}
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.addActions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.com.elarian.hera.proto.WebAction, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.elarian.hera.proto.WebSessionStateEntry} returns this
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.clearActionsList = function() {
  return this.setActionsList([]);
};


/**
 * optional google.protobuf.Timestamp created_at = 6;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 6));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.com.elarian.hera.proto.WebSessionStateEntry} returns this
*/
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.setCreatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.WebSessionStateEntry} returns this
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.clearCreatedAt = function() {
  return this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 7;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 7));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.com.elarian.hera.proto.WebSessionStateEntry} returns this
*/
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.WebSessionStateEntry} returns this
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.clearUpdatedAt = function() {
  return this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.WebSessionStateEntry.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 7) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.elarian.hera.proto.WebState.repeatedFields_ = [1,2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.WebState.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.WebState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.WebState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.WebState.toObject = function(includeInstance, msg) {
  var f, obj = {
    sessionsList: jspb.Message.toObjectList(msg.getSessionsList(),
    proto.com.elarian.hera.proto.WebSessionStateEntry.toObject, includeInstance),
    customerNumbersList: jspb.Message.toObjectList(msg.getCustomerNumbersList(),
    common_pb.CustomerNumber.toObject, includeInstance),
    channelNumbersList: jspb.Message.toObjectList(msg.getChannelNumbersList(),
    common_pb.WebChannelNumber.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.WebState}
 */
proto.com.elarian.hera.proto.WebState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.WebState;
  return proto.com.elarian.hera.proto.WebState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.WebState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.WebState}
 */
proto.com.elarian.hera.proto.WebState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.elarian.hera.proto.WebSessionStateEntry;
      reader.readMessage(value,proto.com.elarian.hera.proto.WebSessionStateEntry.deserializeBinaryFromReader);
      msg.addSessions(value);
      break;
    case 2:
      var value = new common_pb.CustomerNumber;
      reader.readMessage(value,common_pb.CustomerNumber.deserializeBinaryFromReader);
      msg.addCustomerNumbers(value);
      break;
    case 3:
      var value = new common_pb.WebChannelNumber;
      reader.readMessage(value,common_pb.WebChannelNumber.deserializeBinaryFromReader);
      msg.addChannelNumbers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.WebState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.WebState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.WebState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.WebState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSessionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.com.elarian.hera.proto.WebSessionStateEntry.serializeBinaryToWriter
    );
  }
  f = message.getCustomerNumbersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      common_pb.CustomerNumber.serializeBinaryToWriter
    );
  }
  f = message.getChannelNumbersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      common_pb.WebChannelNumber.serializeBinaryToWriter
    );
  }
};


/**
 * repeated WebSessionStateEntry sessions = 1;
 * @return {!Array<!proto.com.elarian.hera.proto.WebSessionStateEntry>}
 */
proto.com.elarian.hera.proto.WebState.prototype.getSessionsList = function() {
  return /** @type{!Array<!proto.com.elarian.hera.proto.WebSessionStateEntry>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.elarian.hera.proto.WebSessionStateEntry, 1));
};


/**
 * @param {!Array<!proto.com.elarian.hera.proto.WebSessionStateEntry>} value
 * @return {!proto.com.elarian.hera.proto.WebState} returns this
*/
proto.com.elarian.hera.proto.WebState.prototype.setSessionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.com.elarian.hera.proto.WebSessionStateEntry=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.elarian.hera.proto.WebSessionStateEntry}
 */
proto.com.elarian.hera.proto.WebState.prototype.addSessions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.com.elarian.hera.proto.WebSessionStateEntry, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.elarian.hera.proto.WebState} returns this
 */
proto.com.elarian.hera.proto.WebState.prototype.clearSessionsList = function() {
  return this.setSessionsList([]);
};


/**
 * repeated CustomerNumber customer_numbers = 2;
 * @return {!Array<!proto.com.elarian.hera.proto.CustomerNumber>}
 */
proto.com.elarian.hera.proto.WebState.prototype.getCustomerNumbersList = function() {
  return /** @type{!Array<!proto.com.elarian.hera.proto.CustomerNumber>} */ (
    jspb.Message.getRepeatedWrapperField(this, common_pb.CustomerNumber, 2));
};


/**
 * @param {!Array<!proto.com.elarian.hera.proto.CustomerNumber>} value
 * @return {!proto.com.elarian.hera.proto.WebState} returns this
*/
proto.com.elarian.hera.proto.WebState.prototype.setCustomerNumbersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.com.elarian.hera.proto.CustomerNumber=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.elarian.hera.proto.CustomerNumber}
 */
proto.com.elarian.hera.proto.WebState.prototype.addCustomerNumbers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.com.elarian.hera.proto.CustomerNumber, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.elarian.hera.proto.WebState} returns this
 */
proto.com.elarian.hera.proto.WebState.prototype.clearCustomerNumbersList = function() {
  return this.setCustomerNumbersList([]);
};


/**
 * repeated WebChannelNumber channel_numbers = 3;
 * @return {!Array<!proto.com.elarian.hera.proto.WebChannelNumber>}
 */
proto.com.elarian.hera.proto.WebState.prototype.getChannelNumbersList = function() {
  return /** @type{!Array<!proto.com.elarian.hera.proto.WebChannelNumber>} */ (
    jspb.Message.getRepeatedWrapperField(this, common_pb.WebChannelNumber, 3));
};


/**
 * @param {!Array<!proto.com.elarian.hera.proto.WebChannelNumber>} value
 * @return {!proto.com.elarian.hera.proto.WebState} returns this
*/
proto.com.elarian.hera.proto.WebState.prototype.setChannelNumbersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.com.elarian.hera.proto.WebChannelNumber=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.elarian.hera.proto.WebChannelNumber}
 */
proto.com.elarian.hera.proto.WebState.prototype.addChannelNumbers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.com.elarian.hera.proto.WebChannelNumber, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.elarian.hera.proto.WebState} returns this
 */
proto.com.elarian.hera.proto.WebState.prototype.clearChannelNumbersList = function() {
  return this.setChannelNumbersList([]);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.com.elarian.hera.proto.WebEvent.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.com.elarian.hera.proto.WebEvent.EventCase = {
  EVENT_NOT_SET: 0,
  STATE_ADOPTED: 1,
  ENTITY_DECOMMISSIONED: 2,
  ACTION: 3
};

/**
 * @return {proto.com.elarian.hera.proto.WebEvent.EventCase}
 */
proto.com.elarian.hera.proto.WebEvent.prototype.getEventCase = function() {
  return /** @type {proto.com.elarian.hera.proto.WebEvent.EventCase} */(jspb.Message.computeOneofCase(this, proto.com.elarian.hera.proto.WebEvent.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.WebEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.WebEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.WebEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.WebEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    stateAdopted: (f = msg.getStateAdopted()) && proto.com.elarian.hera.proto.WebStateAdoptedEvent.toObject(includeInstance, f),
    entityDecommissioned: (f = msg.getEntityDecommissioned()) && proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.toObject(includeInstance, f),
    action: (f = msg.getAction()) && proto.com.elarian.hera.proto.WebActionEvent.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.WebEvent}
 */
proto.com.elarian.hera.proto.WebEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.WebEvent;
  return proto.com.elarian.hera.proto.WebEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.WebEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.WebEvent}
 */
proto.com.elarian.hera.proto.WebEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.elarian.hera.proto.WebStateAdoptedEvent;
      reader.readMessage(value,proto.com.elarian.hera.proto.WebStateAdoptedEvent.deserializeBinaryFromReader);
      msg.setStateAdopted(value);
      break;
    case 2:
      var value = new proto.com.elarian.hera.proto.WebEntityDecommissionedEvent;
      reader.readMessage(value,proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.deserializeBinaryFromReader);
      msg.setEntityDecommissioned(value);
      break;
    case 3:
      var value = new proto.com.elarian.hera.proto.WebActionEvent;
      reader.readMessage(value,proto.com.elarian.hera.proto.WebActionEvent.deserializeBinaryFromReader);
      msg.setAction(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.WebEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.WebEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.WebEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.WebEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStateAdopted();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.com.elarian.hera.proto.WebStateAdoptedEvent.serializeBinaryToWriter
    );
  }
  f = message.getEntityDecommissioned();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.serializeBinaryToWriter
    );
  }
  f = message.getAction();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.com.elarian.hera.proto.WebActionEvent.serializeBinaryToWriter
    );
  }
};


/**
 * optional WebStateAdoptedEvent state_adopted = 1;
 * @return {?proto.com.elarian.hera.proto.WebStateAdoptedEvent}
 */
proto.com.elarian.hera.proto.WebEvent.prototype.getStateAdopted = function() {
  return /** @type{?proto.com.elarian.hera.proto.WebStateAdoptedEvent} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.WebStateAdoptedEvent, 1));
};


/**
 * @param {?proto.com.elarian.hera.proto.WebStateAdoptedEvent|undefined} value
 * @return {!proto.com.elarian.hera.proto.WebEvent} returns this
*/
proto.com.elarian.hera.proto.WebEvent.prototype.setStateAdopted = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.com.elarian.hera.proto.WebEvent.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.WebEvent} returns this
 */
proto.com.elarian.hera.proto.WebEvent.prototype.clearStateAdopted = function() {
  return this.setStateAdopted(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.WebEvent.prototype.hasStateAdopted = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional WebEntityDecommissionedEvent entity_decommissioned = 2;
 * @return {?proto.com.elarian.hera.proto.WebEntityDecommissionedEvent}
 */
proto.com.elarian.hera.proto.WebEvent.prototype.getEntityDecommissioned = function() {
  return /** @type{?proto.com.elarian.hera.proto.WebEntityDecommissionedEvent} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.WebEntityDecommissionedEvent, 2));
};


/**
 * @param {?proto.com.elarian.hera.proto.WebEntityDecommissionedEvent|undefined} value
 * @return {!proto.com.elarian.hera.proto.WebEvent} returns this
*/
proto.com.elarian.hera.proto.WebEvent.prototype.setEntityDecommissioned = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.com.elarian.hera.proto.WebEvent.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.WebEvent} returns this
 */
proto.com.elarian.hera.proto.WebEvent.prototype.clearEntityDecommissioned = function() {
  return this.setEntityDecommissioned(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.WebEvent.prototype.hasEntityDecommissioned = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional WebActionEvent action = 3;
 * @return {?proto.com.elarian.hera.proto.WebActionEvent}
 */
proto.com.elarian.hera.proto.WebEvent.prototype.getAction = function() {
  return /** @type{?proto.com.elarian.hera.proto.WebActionEvent} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.WebActionEvent, 3));
};


/**
 * @param {?proto.com.elarian.hera.proto.WebActionEvent|undefined} value
 * @return {!proto.com.elarian.hera.proto.WebEvent} returns this
*/
proto.com.elarian.hera.proto.WebEvent.prototype.setAction = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.com.elarian.hera.proto.WebEvent.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.WebEvent} returns this
 */
proto.com.elarian.hera.proto.WebEvent.prototype.clearAction = function() {
  return this.setAction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.WebEvent.prototype.hasAction = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.WebStateAdoptedEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.WebStateAdoptedEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.WebStateAdoptedEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.WebStateAdoptedEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    orgId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    customerId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    cxnProps: (f = msg.getCxnProps()) && common_pb.AppConnectionProps.toObject(includeInstance, f),
    adoptedCustomerId: jspb.Message.getFieldWithDefault(msg, 5, ""),
    adoptedState: (f = msg.getAdoptedState()) && proto.com.elarian.hera.proto.WebState.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.WebStateAdoptedEvent}
 */
proto.com.elarian.hera.proto.WebStateAdoptedEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.WebStateAdoptedEvent;
  return proto.com.elarian.hera.proto.WebStateAdoptedEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.WebStateAdoptedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.WebStateAdoptedEvent}
 */
proto.com.elarian.hera.proto.WebStateAdoptedEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrgId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCustomerId(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 4:
      var value = new common_pb.AppConnectionProps;
      reader.readMessage(value,common_pb.AppConnectionProps.deserializeBinaryFromReader);
      msg.setCxnProps(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setAdoptedCustomerId(value);
      break;
    case 6:
      var value = new proto.com.elarian.hera.proto.WebState;
      reader.readMessage(value,proto.com.elarian.hera.proto.WebState.deserializeBinaryFromReader);
      msg.setAdoptedState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.WebStateAdoptedEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.WebStateAdoptedEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.WebStateAdoptedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.WebStateAdoptedEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrgId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCustomerId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCxnProps();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      common_pb.AppConnectionProps.serializeBinaryToWriter
    );
  }
  f = message.getAdoptedCustomerId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getAdoptedState();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.com.elarian.hera.proto.WebState.serializeBinaryToWriter
    );
  }
};


/**
 * optional string org_id = 1;
 * @return {string}
 */
proto.com.elarian.hera.proto.WebStateAdoptedEvent.prototype.getOrgId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.WebStateAdoptedEvent} returns this
 */
proto.com.elarian.hera.proto.WebStateAdoptedEvent.prototype.setOrgId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string customer_id = 2;
 * @return {string}
 */
proto.com.elarian.hera.proto.WebStateAdoptedEvent.prototype.getCustomerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.WebStateAdoptedEvent} returns this
 */
proto.com.elarian.hera.proto.WebStateAdoptedEvent.prototype.setCustomerId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.Timestamp timestamp = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.com.elarian.hera.proto.WebStateAdoptedEvent.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.com.elarian.hera.proto.WebStateAdoptedEvent} returns this
*/
proto.com.elarian.hera.proto.WebStateAdoptedEvent.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.WebStateAdoptedEvent} returns this
 */
proto.com.elarian.hera.proto.WebStateAdoptedEvent.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.WebStateAdoptedEvent.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional AppConnectionProps cxn_props = 4;
 * @return {?proto.com.elarian.hera.proto.AppConnectionProps}
 */
proto.com.elarian.hera.proto.WebStateAdoptedEvent.prototype.getCxnProps = function() {
  return /** @type{?proto.com.elarian.hera.proto.AppConnectionProps} */ (
    jspb.Message.getWrapperField(this, common_pb.AppConnectionProps, 4));
};


/**
 * @param {?proto.com.elarian.hera.proto.AppConnectionProps|undefined} value
 * @return {!proto.com.elarian.hera.proto.WebStateAdoptedEvent} returns this
*/
proto.com.elarian.hera.proto.WebStateAdoptedEvent.prototype.setCxnProps = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.WebStateAdoptedEvent} returns this
 */
proto.com.elarian.hera.proto.WebStateAdoptedEvent.prototype.clearCxnProps = function() {
  return this.setCxnProps(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.WebStateAdoptedEvent.prototype.hasCxnProps = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string adopted_customer_id = 5;
 * @return {string}
 */
proto.com.elarian.hera.proto.WebStateAdoptedEvent.prototype.getAdoptedCustomerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.WebStateAdoptedEvent} returns this
 */
proto.com.elarian.hera.proto.WebStateAdoptedEvent.prototype.setAdoptedCustomerId = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional WebState adopted_state = 6;
 * @return {?proto.com.elarian.hera.proto.WebState}
 */
proto.com.elarian.hera.proto.WebStateAdoptedEvent.prototype.getAdoptedState = function() {
  return /** @type{?proto.com.elarian.hera.proto.WebState} */ (
    jspb.Message.getWrapperField(this, proto.com.elarian.hera.proto.WebState, 6));
};


/**
 * @param {?proto.com.elarian.hera.proto.WebState|undefined} value
 * @return {!proto.com.elarian.hera.proto.WebStateAdoptedEvent} returns this
*/
proto.com.elarian.hera.proto.WebStateAdoptedEvent.prototype.setAdoptedState = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.WebStateAdoptedEvent} returns this
 */
proto.com.elarian.hera.proto.WebStateAdoptedEvent.prototype.clearAdoptedState = function() {
  return this.setAdoptedState(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.WebStateAdoptedEvent.prototype.hasAdoptedState = function() {
  return jspb.Message.getField(this, 6) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.WebEntityDecommissionedEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    orgId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    customerId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    cxnProps: (f = msg.getCxnProps()) && common_pb.AppConnectionProps.toObject(includeInstance, f),
    newCustomerId: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.WebEntityDecommissionedEvent}
 */
proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.WebEntityDecommissionedEvent;
  return proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.WebEntityDecommissionedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.WebEntityDecommissionedEvent}
 */
proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrgId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCustomerId(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 4:
      var value = new common_pb.AppConnectionProps;
      reader.readMessage(value,common_pb.AppConnectionProps.deserializeBinaryFromReader);
      msg.setCxnProps(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setNewCustomerId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.WebEntityDecommissionedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrgId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCustomerId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCxnProps();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      common_pb.AppConnectionProps.serializeBinaryToWriter
    );
  }
  f = message.getNewCustomerId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string org_id = 1;
 * @return {string}
 */
proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.prototype.getOrgId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.WebEntityDecommissionedEvent} returns this
 */
proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.prototype.setOrgId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string customer_id = 2;
 * @return {string}
 */
proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.prototype.getCustomerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.WebEntityDecommissionedEvent} returns this
 */
proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.prototype.setCustomerId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.Timestamp timestamp = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.com.elarian.hera.proto.WebEntityDecommissionedEvent} returns this
*/
proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.WebEntityDecommissionedEvent} returns this
 */
proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional AppConnectionProps cxn_props = 4;
 * @return {?proto.com.elarian.hera.proto.AppConnectionProps}
 */
proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.prototype.getCxnProps = function() {
  return /** @type{?proto.com.elarian.hera.proto.AppConnectionProps} */ (
    jspb.Message.getWrapperField(this, common_pb.AppConnectionProps, 4));
};


/**
 * @param {?proto.com.elarian.hera.proto.AppConnectionProps|undefined} value
 * @return {!proto.com.elarian.hera.proto.WebEntityDecommissionedEvent} returns this
*/
proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.prototype.setCxnProps = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.WebEntityDecommissionedEvent} returns this
 */
proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.prototype.clearCxnProps = function() {
  return this.setCxnProps(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.prototype.hasCxnProps = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string new_customer_id = 5;
 * @return {string}
 */
proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.prototype.getNewCustomerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.WebEntityDecommissionedEvent} returns this
 */
proto.com.elarian.hera.proto.WebEntityDecommissionedEvent.prototype.setNewCustomerId = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.elarian.hera.proto.WebActionEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.com.elarian.hera.proto.WebActionEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.elarian.hera.proto.WebActionEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.WebActionEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    orgId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    customerId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    appId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    cxnProps: (f = msg.getCxnProps()) && common_pb.AppConnectionProps.toObject(includeInstance, f),
    sessionId: jspb.Message.getFieldWithDefault(msg, 6, ""),
    customerNumber: (f = msg.getCustomerNumber()) && common_pb.CustomerNumber.toObject(includeInstance, f),
    channelNumber: (f = msg.getChannelNumber()) && common_pb.WebChannelNumber.toObject(includeInstance, f),
    action: (f = msg.getAction()) && common_pb.WebAction.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.elarian.hera.proto.WebActionEvent}
 */
proto.com.elarian.hera.proto.WebActionEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.elarian.hera.proto.WebActionEvent;
  return proto.com.elarian.hera.proto.WebActionEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.elarian.hera.proto.WebActionEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.elarian.hera.proto.WebActionEvent}
 */
proto.com.elarian.hera.proto.WebActionEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrgId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCustomerId(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setAppId(value);
      break;
    case 5:
      var value = new common_pb.AppConnectionProps;
      reader.readMessage(value,common_pb.AppConnectionProps.deserializeBinaryFromReader);
      msg.setCxnProps(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setSessionId(value);
      break;
    case 7:
      var value = new common_pb.CustomerNumber;
      reader.readMessage(value,common_pb.CustomerNumber.deserializeBinaryFromReader);
      msg.setCustomerNumber(value);
      break;
    case 8:
      var value = new common_pb.WebChannelNumber;
      reader.readMessage(value,common_pb.WebChannelNumber.deserializeBinaryFromReader);
      msg.setChannelNumber(value);
      break;
    case 9:
      var value = new common_pb.WebAction;
      reader.readMessage(value,common_pb.WebAction.deserializeBinaryFromReader);
      msg.setAction(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.elarian.hera.proto.WebActionEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.elarian.hera.proto.WebActionEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.elarian.hera.proto.WebActionEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.elarian.hera.proto.WebActionEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrgId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCustomerId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getAppId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getCxnProps();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      common_pb.AppConnectionProps.serializeBinaryToWriter
    );
  }
  f = message.getSessionId();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getCustomerNumber();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      common_pb.CustomerNumber.serializeBinaryToWriter
    );
  }
  f = message.getChannelNumber();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      common_pb.WebChannelNumber.serializeBinaryToWriter
    );
  }
  f = message.getAction();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      common_pb.WebAction.serializeBinaryToWriter
    );
  }
};


/**
 * optional string org_id = 1;
 * @return {string}
 */
proto.com.elarian.hera.proto.WebActionEvent.prototype.getOrgId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.WebActionEvent} returns this
 */
proto.com.elarian.hera.proto.WebActionEvent.prototype.setOrgId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string customer_id = 2;
 * @return {string}
 */
proto.com.elarian.hera.proto.WebActionEvent.prototype.getCustomerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.WebActionEvent} returns this
 */
proto.com.elarian.hera.proto.WebActionEvent.prototype.setCustomerId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.Timestamp timestamp = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.com.elarian.hera.proto.WebActionEvent.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.com.elarian.hera.proto.WebActionEvent} returns this
*/
proto.com.elarian.hera.proto.WebActionEvent.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.WebActionEvent} returns this
 */
proto.com.elarian.hera.proto.WebActionEvent.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.WebActionEvent.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string app_id = 4;
 * @return {string}
 */
proto.com.elarian.hera.proto.WebActionEvent.prototype.getAppId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.WebActionEvent} returns this
 */
proto.com.elarian.hera.proto.WebActionEvent.prototype.setAppId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional AppConnectionProps cxn_props = 5;
 * @return {?proto.com.elarian.hera.proto.AppConnectionProps}
 */
proto.com.elarian.hera.proto.WebActionEvent.prototype.getCxnProps = function() {
  return /** @type{?proto.com.elarian.hera.proto.AppConnectionProps} */ (
    jspb.Message.getWrapperField(this, common_pb.AppConnectionProps, 5));
};


/**
 * @param {?proto.com.elarian.hera.proto.AppConnectionProps|undefined} value
 * @return {!proto.com.elarian.hera.proto.WebActionEvent} returns this
*/
proto.com.elarian.hera.proto.WebActionEvent.prototype.setCxnProps = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.WebActionEvent} returns this
 */
proto.com.elarian.hera.proto.WebActionEvent.prototype.clearCxnProps = function() {
  return this.setCxnProps(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.WebActionEvent.prototype.hasCxnProps = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string session_id = 6;
 * @return {string}
 */
proto.com.elarian.hera.proto.WebActionEvent.prototype.getSessionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.elarian.hera.proto.WebActionEvent} returns this
 */
proto.com.elarian.hera.proto.WebActionEvent.prototype.setSessionId = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional CustomerNumber customer_number = 7;
 * @return {?proto.com.elarian.hera.proto.CustomerNumber}
 */
proto.com.elarian.hera.proto.WebActionEvent.prototype.getCustomerNumber = function() {
  return /** @type{?proto.com.elarian.hera.proto.CustomerNumber} */ (
    jspb.Message.getWrapperField(this, common_pb.CustomerNumber, 7));
};


/**
 * @param {?proto.com.elarian.hera.proto.CustomerNumber|undefined} value
 * @return {!proto.com.elarian.hera.proto.WebActionEvent} returns this
*/
proto.com.elarian.hera.proto.WebActionEvent.prototype.setCustomerNumber = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.WebActionEvent} returns this
 */
proto.com.elarian.hera.proto.WebActionEvent.prototype.clearCustomerNumber = function() {
  return this.setCustomerNumber(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.WebActionEvent.prototype.hasCustomerNumber = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional WebChannelNumber channel_number = 8;
 * @return {?proto.com.elarian.hera.proto.WebChannelNumber}
 */
proto.com.elarian.hera.proto.WebActionEvent.prototype.getChannelNumber = function() {
  return /** @type{?proto.com.elarian.hera.proto.WebChannelNumber} */ (
    jspb.Message.getWrapperField(this, common_pb.WebChannelNumber, 8));
};


/**
 * @param {?proto.com.elarian.hera.proto.WebChannelNumber|undefined} value
 * @return {!proto.com.elarian.hera.proto.WebActionEvent} returns this
*/
proto.com.elarian.hera.proto.WebActionEvent.prototype.setChannelNumber = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.WebActionEvent} returns this
 */
proto.com.elarian.hera.proto.WebActionEvent.prototype.clearChannelNumber = function() {
  return this.setChannelNumber(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.WebActionEvent.prototype.hasChannelNumber = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional WebAction action = 9;
 * @return {?proto.com.elarian.hera.proto.WebAction}
 */
proto.com.elarian.hera.proto.WebActionEvent.prototype.getAction = function() {
  return /** @type{?proto.com.elarian.hera.proto.WebAction} */ (
    jspb.Message.getWrapperField(this, common_pb.WebAction, 9));
};


/**
 * @param {?proto.com.elarian.hera.proto.WebAction|undefined} value
 * @return {!proto.com.elarian.hera.proto.WebActionEvent} returns this
*/
proto.com.elarian.hera.proto.WebActionEvent.prototype.setAction = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.elarian.hera.proto.WebActionEvent} returns this
 */
proto.com.elarian.hera.proto.WebActionEvent.prototype.clearAction = function() {
  return this.setAction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.elarian.hera.proto.WebActionEvent.prototype.hasAction = function() {
  return jspb.Message.getField(this, 9) != null;
};


goog.object.extend(exports, proto.com.elarian.hera.proto);
