name: Tests

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run lint
    - run: npm test
      env:
        ORG_ID: ${{ secrets.ORG_ID }}
        APP_ID: ${{ secrets.APP_ID }}
        API_KEY: ${{ secrets.API_KEY }}
        PURSE_ID: ${{ secrets.PURSE_ID }}
        USSD_CODE: ${{ secrets.USSD_CODE }}
        VOICE_NUMBER: ${{ secrets.VOICE_NUMBER }}
        MPESA_PAYBILL: ${{ secrets.MPESA_PAYBILL }}
        SMS_SENDER_ID: ${{ secrets.SMS_SENDER_ID }}
        SMS_SHORT_CODE: ${{ secrets.SMS_SHORT_CODE }}
        TELEGRAM_NUMBER: ${{ secrets.TELEGRAM_NUMBER }}
        WHATSAPP_NUMBER: ${{ secrets.WHATSAPP_NUMBER }}
        MESSENNGER_NUMBER: ${{ secrets.MESSENNGER_NUMBER }}
